### ISSUE TITLE
failover fails resource, PGSQL does not get promotd

### ISSUE THREAD

**Issue by frank3427** [ClusterLabs/PAF#119]
both servers gone into slave mode, 
the slave does not get promoted and the master goes into slave mode
the vip is transferred to second server but the resource is in slave mode

~~~
[root@localhost data]# pcs status
Cluster name: pgcluster
Stack: cman
Current DC: dbs04.prodea-int.net (version 1.1.15-5.el6-e174ec8) - partition with quorum
Last updated: Tue Aug 29 00:17:03 2017          Last change: Mon Aug 28 23:39:18 2017 by root via crm_attribute on dbs03.prodea-int.net

2 nodes and 3 resources configured

Online: [ dbs03.prodea-int.net dbs04.prodea-int.net ]

Full list of resources:

 pg-vip (ocf::heartbeat:IPaddr2):       Started dbs03.prodea-int.net
 Master/Slave Set: postgres-ha [postgres]
     Slaves: [ dbs03.prodea-int.net dbs04.prodea-int.net ]

Daemon Status:
  cman: active/disabled
  corosync: active/disabled
  pacemaker: active/enabled
  pcsd: active/enabled


[root@localhost data]# pcs resource move --master postgres-ha dbs04.prodea-int.net
[root@localhost data]# pcs status
Cluster name: pgcluster
Stack: cman
Current DC: dbs04.prodea-int.net (version 1.1.15-5.el6-e174ec8) - partition with quorum
Last updated: Tue Aug 29 03:34:28 2017          Last change: Tue Aug 29 03:34:21 2017 by root via crm_attribute on dbs03.prodea-int.net

2 nodes and 3 resources configured

Online: [ dbs03.prodea-int.net dbs04.prodea-int.net ]

Full list of resources:

 pg-vip (ocf::heartbeat:IPaddr2):       Started dbs03.prodea-int.net
 Master/Slave Set: postgres-ha [postgres]
     postgres   (ocf::heartbeat:pgsqlms):       FAILED dbs03.prodea-int.net
     Slaves: [ dbs04.prodea-int.net ]

Failed Actions:
* postgres_monitor_16000 on dbs03.prodea-int.net 'master' (8): call=16, status=complete, exitreason='none',
    last-rc-change='Tue Aug 29 03:34:21 2017', queued=0ms, exec=1391ms


Daemon Status:
  cman: active/disabled
  corosync: active/disabled
  pacemaker: active/enabled
  pcsd: active/enabled

[root@localhost data]# pcs status
Cluster name: pgcluster
Stack: cman
Current DC: dbs04.prodea-int.net (version 1.1.15-5.el6-e174ec8) - partition with quorum
Last updated: Tue Aug 29 03:35:56 2017          Last change: Tue Aug 29 03:35:27 2017 by root via crm_resource on dbs03.prodea-int.net

2 nodes and 3 resources configured

Online: [ dbs03.prodea-int.net dbs04.prodea-int.net ]

Full list of resources:

 pg-vip (ocf::heartbeat:IPaddr2):       Started dbs04.prodea-int.net
 Master/Slave Set: postgres-ha [postgres]
     Slaves: [ dbs03.prodea-int.net dbs04.prodea-int.net ]

Failed Actions:
* postgres_monitor_16000 on dbs03.prodea-int.net 'master' (8): call=16, status=complete, exitreason='none',
    last-rc-change='Tue Aug 29 03:34:21 2017', queued=0ms, exec=1391ms


Daemon Status:
  cman: active/disabled
  corosync: active/disabled
  pacemaker: active/enabled
  pcsd: active/enabled
~~~

**Comment by frank3427** [comment]
Am i missing something in the resource definition?


[root@localhost data]# pcs resource show --full
 Resource: pg-vip (class=ocf provider=heartbeat type=IPaddr2)
  Attributes: ip=172.24.2.241 cidr_netmask=24
  Operations: start interval=0s timeout=20s (pg-vip-start-interval-0s)
              stop interval=0s timeout=20s (pg-vip-stop-interval-0s)
              monitor interval=10s (pg-vip-monitor-interval-10s)
 Master: postgres-ha
  Meta Attrs: master-node-max=1 master-max=1 clone-max=2 notify=True clone-node-max=1 
  Resource: postgres (class=ocf provider=heartbeat type=pgsqlms)
   Attributes: pgdata=/var/lib/pgsql/9.6/data pgport=5432 bindir=/usr/pgsql-9.6/bin recovery_template=/var/lib/pgsql/9.6/data/../recovery.conf.pgcluster.pcmk
   Operations: start interval=0s timeout=60s (postgres-start-interval-0s)
               stop interval=0s timeout=60s (postgres-stop-interval-0s)
               promote interval=0s timeout=30s (postgres-promote-interval-0s)
               demote interval=0s timeout=120s (postgres-demote-interval-0s)
               notify interval=0s timeout=60s (postgres-notify-interval-0s)
               monitor interval=15s role=Master timeout=10s (postgres-monitor-interval-15s)
               monitor interval=16s role=Slave timeout=10s (postgres-monitor-interval-16s)
[root@localhost data]#

**Comment by ioguix** [comment]
Hi,

First, you are missing fencing resource(s). Don't expect Pacemaker/PAF to react appropriately without them. your cluster might end up being stuck waiting for a human action without it.

Second, you have no master in the first status, so your `move --master` can not work. Is it a first start? How long did you wait? Sometime, the cluster is not able to promote the master immediately after the startup and trigger it during the next cluster recheck (see pacemaker property `cluster-recheck-interval`).

Now your cluster has been started with all node as standby, PAF will not be able to detect your master anymore. You might want to promote the master yourself using the following command:

~~~
crm_master -N <nodename> -l forever -r pgsqld -v 1
~~~

**Comment by YanChii** [comment]
Hi guys,

as this is a result of adapting my ansible [PAF cluster role](https://github.com/YanChii/ansible-role-postgres-ha) to centos 6, I'm posting more info from my lab setup:

The main problem seems to be that the pgsqlms has problem determining the other node's LSN.

```
# pcs resource debug-promote postgres --full
Error performing operation: Operation not permitted
Operation promote for postgres:0 (ocf:heartbeat:pgsqlms) returned 1
 >  stdout: /tmp:5432 - accepting connections
 >  stderr: pgsqlms(postgres:0)[3653]: 2017/08/29_09:01:04  DEBUG: _runas: launching as "postgres" command "/usr/pgsql-9.6/bin/pg_isready -h /tmp -p 5432"
 >  stderr: pgsqlms(postgres:0)[3653]: 2017/08/29_09:01:04  DEBUG: pgsql_monitor: instance "postgres:0" is listening
 >  stderr: pgsqlms(postgres:0)[3653]: 2017/08/29_09:01:04  DEBUG: _query: psql return code: 0
 >  stderr: pgsqlms(postgres:0)[3653]: 2017/08/29_09:01:04  DEBUG: _query: @res: [
 >  stderr:           [
 >  stderr:             't'
 >  stderr:           ]
 >  stderr:         ]
 >  stderr:
 >  stderr: pgsqlms(postgres:0)[3653]: 2017/08/29_09:01:04  DEBUG: _confirm_role: instance postgres:0 is a secondary
 >  stderr: pgsqlms(postgres:0)[3653]: 2017/08/29_09:01:04  DEBUG: pgsql_promote: "postgres:0" currently running as a standby
 >  stderr: pgsqlms(postgres:0)[3653]: 2017/08/29_09:01:04  DEBUG: pgsql_promote: checking if current node is the best candidate for promotion
 >  stderr: 2017/08/29_09:01:04  CRIT: pgsql_promote: can not get current node LSN location
```
local node:
```
# crm_attribute --lifetime reboot --type status --name lsn_location --node centos6-1 --get-value
scope=status  name=lsn_location value=0/3000000
```
remote node (the same result is also when I issue the command remotely):
```
# crm_attribute --lifetime reboot --type status --name lsn_location --node centos6-2 --get-value
scope=status  name=lsn_location value=(null)
Error performing operation: No such device or address
```
```
# corosync -v
Corosync Cluster Engine, version '1.4.7'
Copyright (c) 2006-2009 Red Hat, Inc.

# pacemakerd --version
Pacemaker 1.1.15-5.el6
Written by Andrew Beekhof

# pcs --version
0.9.155

# rpm -qa|grep paf
resource-agents-paf-1.1.0-1.noarch
```

Jan

**Comment by ioguix** [comment]
Hi @YanChii!

Thank you for sharing this ansible role and helping here. Maybe we should open some documentation page on PAF website to aggregate and list various project around PAF, including yours?

Back to the subject, unfortunately, you can not use `pcs resource debug-promote` (which calls `crm_resource --force-promote` behind the scene). PAF requires both notify actions `pre-promote` and `post-promote` to work correctly. 

> The main problem seems to be that the pgsqlms has problem determining the other node's LSN

Because these LSN are set by other nodes during the pre-promote notify action which is not called during a `--force-promote`.

**Comment by blogh** [comment]
hi, @YanChii That's a nice project you have here !

**Comment by YanChii** [comment]
Thanks @ioguix & @blogh.
If you want to add my project on the PAF website, I'm all in. I also want to publish the project on Ansible Galaxy. If it can help somebody, it will be great.

Anyway, I still can't get PAF working on centos 6. I know there have been several issues regarding this. Probably I'm doing something wrong but I can't figure out what is it. The ansible role builds the PAF cluster consistently but the cluster refuses to promote any node (I'm talking only about [centos 6 support](https://github.com/YanChii/ansible-role-postgres-ha/tree/centos6).. centos 7 works without an issue).
The `crm_master` command you wrote earlier does not trigger any action. 

What options I have to debug it? 
Adding `<logging debug="on"/>` to the `cluster.conf` didn't help. I ended up editing `OCF_Functions.pm` to print all debug logs by default. But even with logs enabled, I see no error.

Thanks for help.

Jan.

**Comment by ioguix** [comment]
Hi @YanChii,

> What options I have to debug it?

Edit `/etc/sysconfig/pacemaker` on all your nodes and set `PCMK_debug=yes`.

**Comment by ioguix** [comment]
btw, what version are you using under CentOS 6?

**Comment by frank3427** [comment]
# corosync -v
Corosync Cluster Engine, version '1.4.7'
Copyright (c) 2006-2009 Red Hat, Inc.

# pacemakerd --version
Pacemaker 1.1.15-5.el6
Written by Andrew Beekhof

# pcs --version
0.9.155

# rpm -qa|grep paf
resource-agents-paf-1.1.0-1.noarch

**Comment by frank3427** [comment]
Jan, 

Just did a fresh install and I noticed that the tokens file was not created under /var/lib/pcsd/tokens or /etc/corosync/tokens. I also noticed that there did not exist an /etc/corosync/corosync.conf file either

**Comment by YanChii** [comment]
So it seems that @frank3427 [figured it out](https://github.com/YanChii/ansible-role-postgres-ha/issues/3#issuecomment-326180358). The problem was ordering constraint.
We'll run some tests and let you know.

**Comment by frank3427** [comment]
After a fresh installation on a fresh vm;
[root@localhost ~]# pcs status
Cluster name: pgcluster
Stack: cman
Current DC: dbs03.prodea-int.net (version 1.1.15-5.el6-e174ec8) - partition with quorum
Last updated: Thu Aug 31 15:22:47 2017          Last change: Thu Aug 31 15:22:40 2017 by root via crmd on dbs03.prodea-int.net

2 nodes and 3 resources configured

Online: [ dbs03.prodea-int.net dbs04.prodea-int.net ]

Full list of resources:

 pg-vip (ocf::heartbeat:IPaddr2):       Started dbs03.prodea-int.net
 Master/Slave Set: postgres-ha [postgres]
     Masters: [ dbs03.prodea-int.net ]
     Slaves: [ dbs04.prodea-int.net ]

Daemon Status:
  cman: active/disabled
  corosync: active/disabled
  pacemaker: active/enabled
  pcsd: active/enabled
[root@localhost ~]# pcs resource move  --master postgres-ha  dbs04.prodea-int.net
[root@localhost ~]# pcs resource clear postgres-ha
[root@localhost ~]# pcs status
Cluster name: pgcluster
Stack: cman
Current DC: dbs03.prodea-int.net (version 1.1.15-5.el6-e174ec8) - partition with quorum
Last updated: Thu Aug 31 15:27:49 2017          Last change: Thu Aug 31 15:27:45 2017 by root via crm_resource on dbs03.prodea-int.net

2 nodes and 3 resources configured

Online: [ dbs03.prodea-int.net dbs04.prodea-int.net ]

Full list of resources:

 pg-vip (ocf::heartbeat:IPaddr2):       Started dbs04.prodea-int.net
 Master/Slave Set: postgres-ha [postgres]
     Masters: [ dbs04.prodea-int.net ]
     Slaves: [ dbs03.prodea-int.net ]

Daemon Status:
  cman: active/disabled
  corosync: active/disabled
  pacemaker: active/enabled
  pcsd: active/enabled
[root@localhost ~]# 

this seems to work when I performed failover via PCS, but when I I did a kill -9 pn the PSQL process. it did not fail over, what is did was restart PSQL. 
question:
1) what should be the behavior if the PSQL process was to die?
I was think it would failover and then start PSQL, is that a wrong assumtion

2) I am testing this in VMS, but will be implemented on bare servers. other than fencing via PDU and ILO's. what other fencing can I look at? I would like to isolate the server in question. but not just poweroff or reboot. would like to still be able to remote into the server to diagnose the issue

**Comment by blogh** [comment]
Hi, 

As for question 1, this is expected. If the resource fails on Node 1. Pacemaker tries to restart it on that node. If it succeeds the story ends there. 
If your sabotage your postgresql so that it doesn't restart on 1 (modify postgresql.conf with wrong parameters or delete the xlogs). The restart will fail so the node will be fenced. 

As for question 2.  I don't know of alternative @ioguix  is more knowledgeable than me for that I think. If the server restarts, you can still connect to it (make sure to not auto start the corosync/pacemaker stack).

Hope this helps.
Benoit.

**Comment by ioguix** [comment]
> what should be the behavior if the PSQL process was to die? I was think it would failover and then start PSQL, is that a wrong assumtion

It depends on your `migration-threshold` value. See: http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/_failure_response.html

> I am testing this in VMS, but will be implemented on bare servers. other than fencing via PDU and ILO's. what other fencing can I look at? I would like to isolate the server in question. but not just poweroff or reboot. would like to still be able to remote into the server to diagnose the issue

You could use snmp fencing to shutdown some network ports on manageable switch.
