### ISSUE TITLE
Test Case: Network outage/glitch

### ISSUE THREAD

**Issue by caleno** [ClusterLabs/PAF#123]
Hi there,

I'm working on implementing PAF with a 2 node setup (without fencing), and I am running different 
worst case scenarios to get insights on how the cluster behaves.  

There is one test I've been struggling with and that is network outage/glitch.  

Scenario is simple. 

- Master node loses network connection. (eth0 down)
- After a couple of seconds this is noticed by the cluster and a failover is done. 
- Then network issue is resolved and the old master is put back into cluster as a slave. 

Problem. 

The new slave is not replicating due to time line differences but still an active slave in the cluster. 
Should now the new Master fail a new failover is done to a node which is not in sync and, 
well you get the point. 

Now. 

The question I am always asking my self, what am I doing wrong? 
After many attempts and reading documentation, nudging the pacemaker operations 
parameters and trying different postgres settings, with arching and recovery commands 
I realize that I am stuck. 

So here I am (bothering you guys) to hopefully gain some new perspective and knowledge of 
how PAF is suppose to work (even thou fencing is not use) in such a scenario. 

What I like to happen (disregarding why the failover was  done) is that the node is blocked, 
stopped, put in maintenance or on standby. Anything better then is being put in as a slave
and not in sync. 

I've read some other issue about introducing pg_rewind (which I've also been playing around with) 
to automatically rewind database if there is a timeline error. But that I'll leave for a future solution. 

Right now I just want this (PAF) to work and to be something I can trust will not mess up our clusters should Murphy have a visit and say, I told you so.  (Murphy's law). I want be able to sleep well a night.

So if you have any pointers, please. I'd be grateful. 

And sorry for not sharing any logs or settings right away, I wanted to start the thread first and maybe, maybe the solution is obvious in your eyes, mine has become tired and dim. 

Thanks.

Br,
Lennart

**Comment by blogh** [comment]
Hi,

Because of the outrage, the old master is fenced (whitout fencing any discussion about a cluster is useless). 

It should also not be automatically bring back into the cluster. 
You have to check the old master. There is two solutions:
- Some writes arrived on the old master after the failover. The two postgres have a different history. You have to rewind before reintroducing the (new) slave. (or restore)
- No write arrived on the old master after the failover (it was an "unplanned switchover"). The old master should resume replication without problems. You can add it back into the cluster (= start pacemaker).

Benoit.

**Comment by caleno** [comment]
So it is not possible to just stop or block the failing node regardless of the reason why it failed? 
Is there no operations I can use (that works) which setting for example is **on-fail=block** and will be respected. Or if I only could put it in maintenance mode somehow. 

> Some writes arrived on the old master after the failover. 
I guess because of asynchronous replication. 

>The two postgres have a different history. You have to rewind before reintroducing the (new) slave. (or restore)

And yes, of course, the new slave has to be restored. No problem. But it should for god sake not just be put into the cluster again as if nothing happened. It is my understanding that  when running a streaming replication, whenever a promotion is done the new master starts a new timeline which the old master can't replicate from and then have to be restored. 

There should have be yet another on-fail option and that is run a script or command.
But it seems I have to make use of crontab and a script that searches for the timeline error 
and then make decisions based on its findings. Not pretty and not sleep friendly.

**Comment by caleno** [comment]
We have decided not to use PAF at the moment.

Thanks for feedback and good luck with the project.

**Comment by blogh** [comment]
Hi, 

Sorry, I was aways last week.

> But it should for god sake not just be put into the cluster again as if nothing happened.

Pacemaker starts a ressource as a standby by default.
To avoid what you describe  we don't restart the cluster at the server start time (after the fence). 

>  It is my understanding that when running a streaming replication, whenever a promotion is done the new master starts a new timeline which the old master can't replicate from and then have to be restored.

It all depends on how the promotion is done. If the primary is stopper cleanly, it will stream all it's wal to the stanbies before shutting done. In this case, the old primary can be transformed into a standby without destroying it.  [1][2] 

> There should have be yet another on-fail option and that is run a script or command.

I am relatively new to the project.  My understanding is that until now priority was given to the core functionnality: keeping the service up. Rebuilding the standby can be done after investigation of the problem.

Automatic rebuild (like oracle's reinstate) might come as an option in a future release.

> not sleep friendly

:( I see what you mean...

Thanks for trying PAF ! What are you planning on using ?

[1] [Support clean switchover. ](https://github.com/postgres/postgres/commit/985bd7d49726c9f178558491d31a570d47340459)
[2] [Allow a streaming replication standby to follow a timeline switch. ](https://github.com/postgres/postgres/commit/abfd192b1b5ba5216ac4b1f31dcd553106304b19)
