### ISSUE TITLE
PostgreSQL application log when started by pgsqlms

### ISSUE THREAD

**Issue by ikrustev** [ClusterLabs/PAF#128]
Hi guys,

Sorry for probably asking trivial question, but I'm struggling to find out where Postgres application logs go when started by pgsqlms.

Looking at the code I don't see -l option provided on pg_ctl command line.

And here's the result of the log destination query:

~~~
postgres=# show log_destination;
 log_destination
-----------------
 stderr
(1 row)
~~~

I'm running Ubuntu 17.04 and its startup scripts put the logs here:
/var/log/postgresql/postgresql-9.6-main.log

But when starting via pgsqlms Postgres is not writing there.

I followed the "Debian 8 Two Nodes Quick Start" and it looks pretty good.

Please advice.

**Comment by ioguix** [comment]
Hi,

Indeed, PAF does not give the `-l` argument to `pg_ctl` as the debian startup script does (through `pg_ctl`).

You must setup your logging policy in PostgreSQL itself using: 
* `log_destination=stderr`, `logging_collector=on`, and related parameters `log_filename`, `log_directory`, etc
* **and/or** `log_destination=syslog` and the related `syslog_*` parameters

**Comment by ikrustev** [comment]
Thank you!
