### ISSUE TITLE
Display more informations about pgsql

### ISSUE THREAD

**Issue by StephenSorriaux** [ClusterLabs/PAF#130]
Hello,

I am currently using PAF (2.2.0) with Corosync (2.4.0)/Pacemaker(1.1.16-12.el7_4.7) to manage a 2-nodes postgresql cluster and everything works great.

I just wanted to know if it is possible to get more information about postgresql ? With the "old" RA "pgsql", it was possible to display the type of replication and the baseline :

`Node Attributes:
* Node node1:
    + master-pgsql                      : 100
    + pgsql-data-status                 : STREAMING|SYNC
    + pgsql-status                      : HS:sync   
* Node node2:
    + master-pgsql                      : 1000
    + pgsql-data-status                 : LATEST    
    + pgsql-master-baseline             : 000000000F000000
    + pgsql-status                      : PRI`

**Comment by ioguix** [comment]
Hi @StephenSorriaux,

These informations from the pgsql resource agent are actually some internal attributes the RA "store" in the cluster side for its own purpose.

PAF mostly use temporary and private attributes (stored in the cluster side as well). The only visible attribute is the master score:

* 1001 is the master
* 1000-(10*lag score) are standbies, sorted by lag.

Any other master score means the node is not streaming from the master yet.

I'm not sure we could expose some more information in crm_mon without setting useless attributes and being annoying with the cluster stack with no reasons.

The best I could imagine would be to parse the log file looking for pgsqlms entries or requesting PostgreSQL itself...

You can find useful requests in pgsqlms or check_pgactivity code.

**Comment by StephenSorriaux** [comment]
Thank you a lot for your feedback. Do you thing that is something that can be worth implementing?

**Comment by ioguix** [comment]
No, I don't think that is something worth implementing in PAF, it would add useless cluster event and communication.

In my opinion, this kind of information should be on the metrology/monitoring/cli side if required.
