### ISSUE TITLE
Processing failed op monitor for pgsqld:0 on nodename: unknown error (1)

### ISSUE THREAD

**Issue by Markus-** [ClusterLabs/PAF#132]
Hi,

I was sure my cluster is up and running, but I got a warning every 15 Minutes in my corosync.log (RHEL 7 / HA Addon)

pengine:  warning: unpack_rsc_op_failure:   Processing failed op monitor for pgsqld:0 on nodename: unknown error (1)

Any ideas how to debug?

#pcs status
```
Cluster name: app-name_postgreSQL_cluster
Stack: corosync
Current DC: nodename2 (version 1.1.16-12.el7_4.7-94ff4df) - partition with quorum
Last updated: Wed Apr  4 10:00:01 2018
Last change: Sat Mar 31 02:20:59 2018 by root via crm_attribute on nodename1

2 nodes configured
5 resources configured

Online: [ nodename1 nodename2 ]

Full list of resources:

 ilo2   (stonith:fence_ipmilan):        Started nodename1
 ilo1   (stonith:fence_ipmilan):        Started nodename2
 Resource Group: postgresql
     postgresql_vip     (ocf::heartbeat:IPaddr2):       Started nodename1
 Master/Slave Set: pgsql-ha [pgsqld]
     Masters: [ nodename1 ]
     Slaves: [ nodename2 ]

Failed Actions:
* pgsqld_monitor_15000 on nodename1 'unknown error' (1): call=35, status=Timed Out, exitreason='none',
    last-rc-change='Sat Mar 31 02:20:26 2018', queued=0ms, exec=0ms


Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
```

**Comment by ioguix** [comment]
Hello,


You can set the debug mode in `/etc/sysconfig/pacemaker.conf`:

~~~
PCMK_debug=yes
~~~

It will be extremely chatty though.

However, note the date of that failed action in crm_mon. It is "far" in the past compared to the last event in your cluster. If I'm reading correctly, the error occurred "Sat Mar 31 02:20:26 2018" but the last cluster update occurred on "Wed Apr  4 10:00:01 2018", 4 days later. So it seems to me nothing occurred during 4 days.

Also, note that even with no event, the cluster wakes up every 15 minutes by default to check if there's something to do. See `cluster-recheck-interval` in https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/s-cluster-options.html.

**Comment by Markus-** [comment]
Where can I find details about "pgsqld_monitor_15000". What does the monitor do?

**Comment by ioguix** [comment]
"pgsqld_monitor_15000" is the internal id for the monitor action of the "pgsqld" resource occurring every 15000ms (15s).

You can find what the monitor acton do in PAF resource agent script (called `pgsqlms`). See: https://github.com/ClusterLabs/PAF/blob/master/script/pgsqlms. Look for "sub pgsql_monitor {".

You can find the diagram of the monitor action there: https://github.com/ClusterLabs/PAF/tree/master/docs/dev

However, note that you error was a timeout...Not an error in this action.

**Comment by Markus-** [comment]
Thanks. 
I know it was a timeout - but for further clarification it is easier to know what action timed out.
