### ISSUE TITLE
Avoid "not connected" warning when adding node just for quorum

### ISSUE THREAD

**Issue by timdeluxe** [ClusterLabs/PAF#138]
My situation is very similar to the one described in #109. Of course i have added the location constraint. crm_mon does not complain, however every monitor interval seconds (in my case the proposed 15 seconds) i get the warning in syslog:

`pgsqlms(postgresql)[28200]: WARNING: "quorum_node_name" is not connected to the primary`

I have no good idea, how to solve this. Parsing the cluster config for the fitting location constraint could become quite tricky. Maybe add another config option to exclude a node?

**Comment by ioguix** [comment]
Indeed.

Maybe the solution would be to warn only for the first time, when the master score is not already set to -1000?

Could you test the patch bellow?

~~~diff
diff --git a/script/pgsqlms b/script/pgsqlms
index 4584f78..fcf0cc8 100755
--- a/script/pgsqlms
+++ b/script/pgsqlms
@@ -767,6 +767,11 @@ sub _check_locations {
         # Exclude the current node.
         next if $node eq $nodename;
 
+        # do not warn if the master score is already set to -1000.
+        # this avoid log flooding (gh #138)
+        $node_score = _get_master_score( $node );
+        next if $node_score eq '-1000';
+
         ocf_log( 'warning', '"%s" is not connected to the primary', $node );
         _set_master_score( '-1000', $node );
     }
~~~

**Comment by timdeluxe** [comment]
Good idea!
I tested your patch and it works great!

**Comment by ioguix** [comment]
Great, thank you for your test. I'll add it to the next release then.

Have a good day.
