### ISSUE TITLE
notify=true check should be case insensitive

### ISSUE THREAD

**Issue by YanChii** [ClusterLabs/PAF#141]
Hi,

I've noticed that `crm_resource` command can return ```True``` instead of ```true``` and consequently the resource fails:
```
crm_resource --resource postgres-ha --meta --get-parameter notify
True
```
corosync-2.4.3-4
pacemaker-1.1.19

The correction should be done here:
https://github.com/ClusterLabs/PAF/blob/master/script/pgsqlms#L1272
by adding `lc()` function like this:
```
unless ( lc($ans) eq 'true' ) {
```

Have a nice day.

Jan

**Comment by ioguix** [comment]
Hi,

Thank you for this report!

If I understand well crm_resource's code, it seems to me this value is extracted from XML with no parsing or changes. Here is the underlaying function fetching the requested value:

https://github.com/ClusterLabs/pacemaker/blob/b1c4692cae3e460bc8b7705995c2ea1fe865b9a8/lib/common/xml.c#L4641

Looking at how booleans from CIB are parsed, it seems a bunch of values are accepted: yes, y, true, 1, on and their opposite. See: https://github.com/ClusterLabs/pacemaker/blob/master/lib/common/strings.c#L167

So the fix should be a bit stronger. I'll take care of it in some days, unless you find some time for a pull request in the meantime.

Thanks again!

**Comment by YanChii** [comment]
I've got some time :)
I suspect this one is related to a new pacemaker version because I've never seen it before.

**Comment by ioguix** [comment]
Thank you!
