### ISSUE TITLE
Run pgsql-ha resource only on specific nodes

### ISSUE THREAD

**Issue by Orsopepe** [ClusterLabs/PAF#155]
Hi Guys,

im working on a cluster that should manage different kind of resources including Postgres with PAF.
My cluster has 6 nodes, tree are dedicated to the webserver and the other tree for the database.
i would set my pgsqld/pgsql-ha master/slave resource working only on three nodes instead all of them.
im still struggle with it, cannot achive that, my postgres resource just try sto spread in all nodes of the cluster but i need it only of three of them.

could you guys give me some hint?

many thanks

Orsopepe

**Comment by ioguix** [comment]
Hi,

See the cookbook:

- for RedHat/pcs: https://clusterlabs.github.io/PAF/CentOS-7-admin-cookbook.html#forbidding-a-paf-resource-on-a-node
- for Debian/crm: https://clusterlabs.github.io/PAF/Debian-8-admin-cookbook.html#forbidding-a-paf-resource-on-a-node

**Comment by Orsopepe** [comment]
Thanks for your fast support, I was struggling whit this and didnt pay enough attention to the cookbook.
Thanks for you kindly support, have a good evening.

Orsopepe

**Comment by ioguix** [comment]
You are welcome !

Have a good evening as well.
