### ISSUE TITLE
Failed Resource after hard reset of Master Node

### ISSUE THREAD

**Issue by Orsopepe** [ClusterLabs/PAF#162]
Hi guys, im very close to move my cluster to the production environment (and im very happy for this).
Right now am playing on VMWARE virtual environment before switch to baremetals and everything  is working fine.
Im still testing some disasters scenarios hard resetetting the VM's.
Resetting the master VM, a new master is correctly elected, but the old one didnt had time to demote cause the sudden reset.
when i try to rejoin it into pacemaker, it send me the following error and the fencing system triggers rebooting it:

Failed Resource Actions:
* postgres_stop_0 on TEST2 'unknown error' (1): call=12, status=complete, exitreason='Unexpected state for instance "postgres" (returned 9)',
    last-rc-change='Mon Jan 20 17:43:55 2020', queued=0ms, exec=158ms

so i found a quick way to fix it: 
just recreate the recovery.config file start and stop the postgresql service and then rejoin it trought pacemakeron the old  not demoted master node.

i'd like to understand if this scenario is avoidable trought something missing in my configuration or is something PAF cant handle.

thanks for your time and support

Orsopepe

**Comment by ioguix** [comment]
Hello,

Well, when the cluster tries to probe, start or stop the resource, it detects the state is `FAILED_MASTER` (return code 9), and it doesn't like it at all.

During the stop action, we could (PAF) return `SUCCESS` if the instance is detected as a `FAILED_MASTER` as technically, the instance is really stopped and that's all the cluster wants to know when it calls the stop action. It doesn't care the real state the resource is in, it just want it to be stopped.

But then, it will try again to start it as a standby. And this is where the dragons are waiting to catch us. The failed primary instance might start as a standby and even catch with the new primary, but there is no guaranty it is actually safe from corruptions, especially if it had writes that where not streamed to standbies before being interrupted.

After a failover, you MUST rebuild you old primary. Either use pg_rewind or restore your previous PITR backup (my favorite choice).

See: https://clusterlabs.github.io/PAF/administration.html#failover

Based on the information I have, your current solution is unsafe.

Regards,

**Comment by Orsopepe** [comment]
Thanks for your enlightenments,  really appreciate your explanation, very clear and effective.
Have a good day!

**Comment by ioguix** [comment]
You are welcome. Have a good day too!
