### ISSUE TITLE
A question 

### ISSUE THREAD

**Issue by gogich77** [ClusterLabs/PAF#163]
When to use the Perl or Bash version (https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/pgsql) ?
What is the diff ?

**Comment by ioguix** [comment]
Hello,

Motivations for the perl version are described there: https://clusterlabs.github.io/PAF/FAQ.html#why-new-ra-for-postgresql

If you just need a stateless RA for a shared disk cluster, Bash version is the way to go. Perl version does not support this.

For other scenario, test both and pick your favorite one.
