### ISSUE TITLE
LICENSE/Copyright update

### ISSUE THREAD

**Issue by reslavath** [ClusterLabs/PAF#164]
Hi Team,

Thanks for PAF. we've been validating this since a while. we are happy with the results so far.
we are planning more destructive tests going forward.

we see there is a change recently in License page.
"License: PostgreSQL" is missing in the https://github.com/ClusterLabs/PAF/blob/de924e05aba9921e5e86cec8e1bad18cf5085aed/LICENSE
is it deliberate ?

But under debian copyright we have this "**License: PostgreSQL**".
https://github.com/ClusterLabs/PAF/blob/de924e05aba9921e5e86cec8e1bad18cf5085aed/debian/copyright

can you please help us to understand what is the difference ?

Regards
reslavath

**Comment by ioguix** [comment]
Hello,

The last change is the copyright year update. Nothing else changed.

The LICENSE file follows this template: https://opensource.org/licenses/postgresql

The debian copyright file follows the debian specs: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

There is no difference.

Regards,
