### ISSUE TITLE
question about swap roles

### ISSUE THREAD

**Issue by Orsopepe** [ClusterLabs/PAF#165]
Hi all, 

im testing a dual node cluster with PAF 2.1 and postgres11.
Unfortunally i cant configure any fencing devices but all the network is clustered and bondend.
im asked to do so and i already comunicate all the possible problem to my boss. he knows and take resposability.
anyway i already build everything up and is working.

My question is: 

can swtich roles using :

~~~
# pcs resource move --master pgsql-ha srv2
# pcs resource clear pgsql-ha
~~~

lead to an inconsistent/wrong state?

Many thanks and have a good evening

**Comment by ioguix** [comment]
> im testing a dual node cluster with PAF 2.1 and postgres11.
> Unfortunally i cant configure any fencing devices [...]

This is wrong and will fail soon or later. At least, make sure to have watchdog, but it will not save you without proper fencing. At least, ain't you able to use a shared block device somewhere to poison-pill the other node? Search for poison pill in https://access.redhat.com/articles/2800691 or https://documentation.suse.com/sle-ha/15-SP1/html/SLE-HA-all/cha-ha-fencing.html

> can swtich roles using [...] lead to an inconsistent/wrong state?

This should be safe. PAF controls the whole controlled switch over and raise an error if something wrong happen on the way.

**Comment by Orsopepe** [comment]
Unfortunally i cant use any shared disk to poison-pill the other node, and watchdog doesnt help at all.
Do you know any other methods?
My Boss knows the risks (probably not at all).
Now we failed a test (i was not there) beacause during the pg_basebackup he didnt edit the pg_hba.conf leaving the old IP's and invalidating the replication. and after few switches also the configuration doesnt work anymore.
Sad beacuse i work on it so much time :/

thanks for your precious support i appreciate much.

Pepe

**Comment by ioguix** [comment]
> Do you know any other methods?

Network fencing using fence-mib? Storage fencing on SAN network? Custom fencing device connected to the reset pin of the board (unlikely, I know)? Best: cheap manageable PDU or UPS?

If you can afford an etcd cluster, go for Patroni. One etcd cluster can manage many Patroni/PgSQL two-node clusters.

Last argument: how much would cost data corruption or long downtime because of split-brain compare to a cheap PDU/UPS? Does the data worth less than few hundreds of USD? If yes, I suppose you seek for service high-availability, not data availability. My advice would be to look for a simple solution and architecture. The simple it is, the best.

**Comment by ioguix** [comment]
I thought about something else: if you can setup a light corosync daemon on a third node (existing or not), you can create a qdevice to enable quorum. Quorum+watchdog is good.

I hadn't write doc about this yet. Look for online about corosync qdevice. As far as I understand, one qdevice can be part of multiple Pacemaker cluster.

**Comment by Orsopepe** [comment]
im totally agree with you about data corruption, expecially for production data.
i already expect to be called when something will go wrong. :/
Unfortunally my boss doesnt trust in disk fencing and no PDU/UPS are available for fencing (we can get only energy supply.)
Patroni could be a good solution, but for this project we cant afford it.
can you explain me fence-mib and custom fencing device to reset pin?

3 node qdevice can be a good option as well..

thanks for you time really appreciate.

pepe

**Comment by ioguix** [comment]
if one small qdevice leaving somewhere in the network is a good option, go for it. And again, this small and alone corosync-qdevice daemon is able to take part in multiple independent pacemaker clusters. You'll have quorum+watchdog, which is good enough considering your constraints.

fence-mib fence the network on the switch using SNMP. Cheap fencing as well. Manageable switch start bellow 200USD. See: https://clusterlabs.github.io/PAF/fencing.html#resource-fencing-using-snmp

«custom fencing device to reset pin» require to build an electronic device, eg: https://www.alteeve.com/w/Node_Assassin. Most people will not be able to accept and/or such device :)

**Comment by Orsopepe** [comment]
Thanks for your explanations.
qdevice daemon+watchdong can be a good choice i will give it a try!
Thanks for your advices!
Have a good Weekend!
Pepe

**Comment by ioguix** [comment]
> Have a good Weekend!

You too!
