### ISSUE TITLE
Difference between this RA vs the official one?

### ISSUE THREAD

**Issue by givemeurhats** [ClusterLabs/PAF#166]
I am unable to find any information explaining the difference between this RA and the official one here: https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/pgsql ?

The only thing I found is https://clusterlabs.github.io/PAF/FAQ.html#why-new-ra-for-postgresql but I'm pretty sure that was written when PAF came out.

Thank you in advance.

**Comment by lucius-the** [comment]
I found this: https://clusterlabs.github.io/PAF/FAQ.html#why-new-ra-for-postgresql

But have no idea how up to date that info is.

I would also very much like to know which RA is recommenced for PostgresSQL in 2020. We're planning on using some RA for PostgreSQL 12. Which one is better ?

**Comment by ioguix** [comment]
> The only thing I found is https://clusterlabs.github.io/PAF/FAQ.html#why-new-ra-for-postgresql but I'm pretty sure that was written when PAF came out.

This link is accurate and was written when PAF cam out :)

> I would also very much like to know which RA is recommenced for PostgresSQL in 2020

Well, I suppose I am biased as an author of PAF. But at least I can tell you it is actively maintained.

**Comment by lucius-the** [comment]
How safe is it to use PAF with PostgreSQL 12 at the moment. It's still in RC, any special reason ?

**Comment by ioguix** [comment]
> It's still in RC, any special reason ?

I'm just giving time for tests. I had 2 small fixes between rc1 and rc2. I plan to release next week.
