### ISSUE TITLE
Are Pacemaker version 2 & Chorosync 3 supported ?

### ISSUE THREAD

**Issue by asafo** [ClusterLabs/PAF#168]
Are Pacemaker version 2 & Chorosync 3 supported ?

Or is it workable ?

Using CentOS 8.1 with pcs

10x

**Comment by ioguix** [comment]
Hello @asafo,

Yes, Pacemaker 2/Corosync 3 stack is supported, I was able to build and test a cluster using RHEL8. Vagrant files in `extra` directory supports RH8.

Didn't try with CentOS 8.1 yet, but I see they finally included a new HighAvailability repo. Great ! I'll try to support it soon in the Vagrantfiles as well.
