### ISSUE TITLE
PAF configuration in RHEL 8

### ISSUE THREAD

**Issue by HowardPHX** [ClusterLabs/PAF#169]
Greeting!  Has the installation process changed in RHEL8?  I have installed PAF 2.3.0

Following the Centos 7 instructions, I can create the resource using this command:

~~~
pcs -f cluster1.xml resource create pgsqld ocf:heartbeat:pgsqlms \
    bindir=/usr/bin pgdata=/var/lib/pgsql/data     \
    op start timeout=60s                                         \
    op stop timeout=60s                                          \
    op promote timeout=30s                                       \
    op demote timeout=120s                                       \
    op monitor interval=15s timeout=10s role="Master"            \
    op monitor interval=16s timeout=10s role="Slave"             \
    op notify timeout=60s
~~~

The next step does not work.  it just returns the pcs resource help page as if it doesn't understand master.
~~~
pcs -f cluster1.xml resource master pgsql-ha pgsqld notify=true
~~~
Thanks for reading.  I'm at a loss.

**Comment by HowardPHX** [comment]
I have read that RHEL 8 changed the master/slave to promotable resources and am trying to work out the new syntax.

**Comment by ioguix** [comment]
Hi @HowardPHX,

I hadn't wrote doc for EL8 yet, but I tested PAF using a Vagrantfile to quickly build a cluster.

Here is the relevant file for you:
https://github.com/ClusterLabs/PAF/blob/master/extra/vagrant/3nodes-vip/provision/pacemaker.bash

I'll add some official doc about EL8 very soon.

Regards,

**Comment by HowardPHX** [comment]
Thank you.  This is really helpful.

**Comment by ioguix** [comment]
I just pushed a first version of the quick start for CentOS 8.

https://clusterlabs.github.io/PAF/Quick_Start-CentOS-8.html

Regards,
