### ISSUE TITLE
debian 10 + postgresql 12|: attempting to execute non-existent binary /usr/bin/postgres

### ISSUE THREAD

**Issue by asafo** [ClusterLabs/PAF#170]
Hello,

Using the latest 2.3.0 version, from pgdg packages on debian 10
Getting stopped resources becouse of: Parameter "recovery_target_timeline" MUST be set to 'latest'
The parametes is defined ok, found the root cause in script/pgsqlms line 1338:
        $guc = qx{ $POSTGRES -C recovery_target_timeline -D "$pgdata" $start_opts};

where $POSTGRES=/usr/bin/postgres which does not exist

10x

**Comment by ioguix** [comment]
Hi,

`/usr/bin/postgres` is the default value of `bindir` parameter. Do you set this parameter to the correct path to the postgresql binaries?

**Comment by asafo** [comment]
Thanks
looks like it should be: /usr/lib/postgresql/12/bin

**Comment by ioguix** [comment]
Yes. I suppose, if you are using Debian or derivative. It's depends on the system and the installation method.

Regards
