### ISSUE TITLE
Error: Unecpected state for instance "pgsqld" (returned 9)

### ISSUE THREAD

**Issue by zav2384** [ClusterLabs/PAF#173]
Hello.
I configured a two-node cluster based on Pacameker / Corosync and PAF.
Set up streaming replication. Began to test switching to the slave node in the event of a failure.
Simulate a crash through:
`# kill -9 "pid main process Postgres"`
As a result, the master node goes into reboot, and switching to slave fails
I analyzed the reasons. I came to the conclusion that the problem manifests itself at the moment when a long transaction is performed on the master node (DELETE for several minutes).
Due to the fact that some Postgres processes remain on the master node, Postgres cannot start correctly on the current node and the demote / promote process does not start.
Below I enclose what is recorded in the Pacemaker logs, as well as the remaining processes (pid) of Postgres and the Postgres log

Tell me, is something configured incorrectly for me or should it work like that?
That is, it turns out that any long transaction can interrupt the correct PAF switch?

[pacemaker.log](https://github.com/ClusterLabs/PAF/files/4863301/pacemaker.log)

![pids](https://user-images.githubusercontent.com/41430079/86343107-91af6380-bc69-11ea-8e0d-14f21ad4f296.jpg)
![postgres_log](https://user-images.githubusercontent.com/41430079/86342682-00d88800-bc69-11ea-9188-f0c7a63234f6.jpg)

**Comment by ioguix** [comment]
Hi,

I miss some pieces from the jigsaw.
Could you please provide logs from both nodes?
What is your system/PAF/PostgreSQL version?

**Comment by zav2384** [comment]
Postgres 12
I will specify the versions of packages in the near future.
There are no old logs, so I repeated the test. But previously I turned off the "Stonith Enabled" option (in the "false" state)
If necessary, I can repeat the test with Stonith enabled
The kill command was executed at 15:20 on the pg01 node (master).

[pg01-pacemaker.log](https://github.com/ClusterLabs/PAF/files/4863893/pg01-pacemaker.log)
[pg01-postgresql-2020-07-02_125626.log](https://github.com/ClusterLabs/PAF/files/4863894/pg01-postgresql-2020-07-02_125626.log)
[pg02-pacemaker.log](https://github.com/ClusterLabs/PAF/files/4863895/pg02-pacemaker.log)
[pg02-postgresql-2020-07-02_151727.log](https://github.com/ClusterLabs/PAF/files/4863897/pg02-postgresql-2020-07-02_151727.log)

**Comment by ioguix** [comment]
Stonith is mandatory, no matter what, sorry :/

Could you please make your test with stonith on? Using watchdog is good enough.

**Comment by zav2384** [comment]
I turned on the "Stonith Enabled" 
It seems strange to me that Pacemaker (on pg 02 node) considers unsuccessful an attempt to reload pg 01 node.
In this case, node pg 01 in fact goes into reboot
See the console.txt file

[console.txt](https://github.com/ClusterLabs/PAF/files/4864323/console.txt)
[pg01-pacemaker.log](https://github.com/ClusterLabs/PAF/files/4864324/pg01-pacemaker.log)
[pg01-postgresql-2020-07-02_171824.log](https://github.com/ClusterLabs/PAF/files/4864325/pg01-postgresql-2020-07-02_171824.log)
[pg02-pacemaker.log](https://github.com/ClusterLabs/PAF/files/4864326/pg02-pacemaker.log)
[pg02-postgresql-2020-07-02_172109.log](https://github.com/ClusterLabs/PAF/files/4864327/pg02-postgresql-2020-07-02_172109.log)

**Comment by zav2384** [comment]
pacemaker (2.0.3-x86_64);
corosync (3.0.3.0.18.g89b0d-x86_64);
resource-agents-paf (2.3.0-noarch);
pcs (0.10.5-noarch).

**Comment by ioguix** [comment]
Thank you for the logs.

First, it seems your fencing setup is failing according to this status:

~~~
Failed Fencing Actions:
  * reboot of dir-rx-pg01 failed: delegate=dir-rx-pg02, client=pacemaker-controld.1019535, origin=dir-rx-pg02, last-failed='2020-07-02 17:26:33 +05:00'
~~~

Then, according to your log, I suspect pgsqlms wrongly assume the primary has been recovered during the pre-demote action:

~~~
pgsqlms(pgsqld)[25597]:	Jul 02 17:25:23  INFO: Trying to start failing master "pgsqld"...
pgsqlms(pgsqld)[25597]:	Jul 02 17:25:23  DEBUG: _runas: launching as "postgres" command "/opt/pgpro/ent-12/bin/pg_ctl --pgdata /var/lib/pgpro/ent-12/data -w --timeout 120 start"
pgsqlms(pgsqld)[25597]:	Jul 02 17:25:23  INFO: State is "in production" after recovery attempt
~~~

I suspect the state is `in production` because of the previous state, not because `pg_ctl start` succeed. Because of the rogue postgresql backend, I suspect `pg_ctl` might have failed. This part of the code would deserve some stronger checks. I'll fix this.

However, at the end of the day, the result should be the same: pgsqlms is not responsible to kill rogue backends and hope for them to disappear promptly. The only fast way out is to fence the node so the standby can be promoted. So I suppose your problem is related to you fencing setup.

Surprisingly, I couldn't find in your log decisions or actions from pacemaker's scheduler or fencer, but I'm pretty sure the fencing is not able to fence your node. As long as your old primary is not fenced for sure, the standby can not be promoted by the cluster to avoid split brain scenario.

What system are you using? how/where your logs are collected?

You are using `fence_sbd`, are you using a shared storage with poison pill as fencing method?

Could you share your pacemaker setup using `pcs config show`?

Regards,

**Comment by zav2384** [comment]
>>I suspect the state is in production because of the previous state, not because pg_ctl start succeed. 
- I agree with you.
>>What system are you using? how/where your logs are collected?
- I didn't understand the question. What is meant by a system - an operating system, Linux kernel, or something else?
Part of the logs is fixed in journalctl. If necessary, I can upload this log.
>>I'll fix this.
can you clarify when you can fix this moment (date)?

I use a block device on my storage system (FC SAN). Below are the SBD options:
```
[root@dir-RX-PG01 drm_adm]# sbd -d /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242*1 dump
==Dumping header on disk /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242*1
Header version     : 2.1
UUID               : 2ab0ef83-c387-4d58-b516-1ceca72f55ee
Number of slots    : 255
Sector size        : 512
Timeout (watchdog) : 30
Timeout (allocate) : 2
Timeout (loop)     : 1
Timeout (msgwait)  : 60
==Header on disk /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242*1 is dumped
[root@dir-RX-PG01 drm_adm]# sbd -d /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242*1 list
0       dir-rx-pg01  clear
1       dir-rx-pg02  clear
```

```
/etc/sysconfig/sbd:
# This file has been generated by pcs.
SBD_DEVICE="/dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242*1"
SBD_DELAY_START=yes
SBD_OPTS="-W"
SBD_PACEMAKER=yes
SBD_STARTMODE=always
SBD_WATCHDOG_DEV=/dev/watchdog
SBD_WATCHDOG_TIMEOUT=5
```
`pcs config show`
[pcs_config.txt](https://github.com/ClusterLabs/PAF/files/4867680/pcs_config.txt)

**Comment by zav2384** [comment]
I analyzed the journalctl log. The reboot command (stonith) correctly came from the pg02 node:
```
июл 02 17:25:30 dir-RX-PG01 sbd[20781]: /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242641:   notice: servant_md: Received command reset from dir-rx-pg02 on disk /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242641
июл 02 17:25:30 dir-RX-PG01 sbd[20780]:  warning: inquisitor_child: /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242641 requested a reset
июл 02 17:25:30 dir-RX-PG01 sbd[20780]:    emerg: do_exit: Rebooting system: reboot
-- Reboot --
```
[pg01-journalctl.zip](https://github.com/ClusterLabs/PAF/files/4867814/pg01-journalctl.zip)

**Comment by zav2384** [comment]
The record also confuses me (journalctl):
`Jul 02 17:25:22 dir-RX-PG01 pacemaker-schedulerd [20789]: notice: Watchdog will be used via SBD if fencing is required and **stonith-watchdog-timeout is nonzero**`
but in my configuration stonith-watchdog-timeout = 0

**Comment by ioguix** [comment]
> I didn't understand the question. What is meant by a system - an operating system, Linux kernel, or something else? Part of the logs is fixed in journalctl. If necessary, I can upload this log.

I mean, what is your Linux distribution and version? Where did you find these log files? I'm just surprised to read logs without schedulerd, fenced, controllerd, etc. But it seems logs from your journalctl might be more standard, based on your last messages...
If you can share them, for all the nodes, especially if there's more information there, that might be useful.

> can you clarify when you can fix this moment (date)?

Not yet. I'm really not sure of my schedule right now. But "soon", for sure. Hopefully next week. If you are able to help, in `pgsql_notify_pre_demote`, add a test on the return code from `_pg_ctl_start()` and maybe replace `%cdata = _get_controldata()` with a call + check on `$rc = pgsql_monitor()`...and report here :)

But notify action return code are ignore by pacemaker. So we can not raise an error from there to interrupt the transition. The next action being the demote, the error raise from there already anyway. The fix I am speaking about here is just for clean and coherent logs.

> `Timeout (msgwait)  : 60`

I am a bit surprised of such large timeout.

> I analyzed the journalctl log. The reboot command (stonith) correctly came from the pg02 node:

Base on your crm_mon output, the fencing did not happen...There's something strange here.

What is the output of the following commands (from dir-rx-pg01)?

~~~
pcs stonith history
pcs stonith sbd status
pcs stonith sbd device message /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242*1 dir-rx-pg02 test
~~~

Then check on pg02 it received the test message: `journalctl -u sbd |grep 'Received command test'`

> The record also confuses me (journalctl): `Watchdog will be used via SBD if fencing is required and stonith-watchdog-timeout is nonzero`

This means Pacemaker can rely on watchdog self-fencing if you set `stonith-watchdog-timeout` greater than 0. I would recommend 10 here (twice your `SBD_WATCHDOG_TIMEOUT` for security reason). See "Enable stonith-watchdog-timeout fencing" in https://access.redhat.com/articles/3099231 .

**Comment by zav2384** [comment]
Our communication in this thread led me to several ideas.
I recreated SBD with less timeouts.
```
# sbd -d /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242641 dump
==Dumping header on disk /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242641
Header version     : 2.1
UUID               : e17b524e-c348-4d4c-8e13-54d068b20213
Number of slots    : 255
Sector size        : 512
Timeout (watchdog) : 15
Timeout (allocate) : 2
Timeout (loop)     : 1
Timeout (msgwait)  : 30
==Header on disk /dev/disk/by-id/scsi-36000c29c7c805f4d49843462bd242641 is dumped
```
After that, I adjusted the following timeouts:

- stonith-timeout -> 36s (in cluster global properties )
- stonith-watchdog-timeout -> 10 (in cluster global properties )
- power_timeout -> 32 (in cluster fence_device properties)

Next simulated a kill-9 crash
The Stonith mechanism worked correctly:
```
[root@dir-RX-PG02 tmp_backup]# pcs stonith history
reboot of dir-rx-pg01 successful: delegate=dir-rx-pg02, client=pacemaker-controld.1313269, origin=dir-rx-pg02, completed='2020-07-03 16:15:35 +05:00'
1 events
 found
```
Switching was successful on the pg02 slave node! :)

Next, I turned on Pacemaker on pg01 after rebooting.
And here the Stonith mechanism worked again and the node went into reboot again.
```
[root@dir-RX-PG02 tmp_backup]# pcs stonith history
reboot of dir-rx-pg01 successful: delegate=dir-rx-pg02, client=pacemaker-controld.1313269, origin=dir-rx-pg02, completed='2020-07-03 16:15:35 +05:00'
reboot of dir-rx-pg01 successful: delegate=dir-rx-pg02, client=pacemaker-controld.1313269, origin=dir-rx-pg02, completed='2020-07-03 16:13:07 +05:00'
2 events found
```
Now the problem is that it is impossible to return the pg 01 node to the cluster simply by turning on Pacemaker. Or will I always be forced to restore from the master node (or using pg_rewind) after the Stonith mechanism is triggered?

[pg01-journalctl.log](https://github.com/ClusterLabs/PAF/files/4869517/pg01-journalctl.log)
[pg02-journalctl.log](https://github.com/ClusterLabs/PAF/files/4869524/pg02-journalctl.log)

**Comment by ioguix** [comment]
Hi,

Great. Make sure to review your fencing/watchdog/sbd timeout closely, they must be coherent with each others. RH online resources are great readings.

> Now the problem is that it is impossible to return the pg 01 node to the cluster simply by turning on Pacemaker. Or will I always be forced to manually restore from the master node (pg_basebackup or using pg_rewind) after the Stonith mechanism is triggered ?

Indeed. It is not recommended to failback a PostgreSQL instance without rebuild/resync actions after an ungraceful shutdown. You have to either rebuild it or resync it using eg. pg_rewind or your PITR favorite tool. Then start the cluster again on the node. See https://clusterlabs.github.io/PAF/administration.html#failover

**Comment by zav2384** [comment]
Ok, good!
Thanks!!!

**Comment by ioguix** [comment]
You are welcome!
