### ISSUE TITLE
Do we have any avaliable guide on how to build Postgresql 12 HA cluster with PAF?

### ISSUE THREAD

**Issue by dashng** [ClusterLabs/PAF#174]
On the production we are using postgresql-10, the customer request to upgrade the PG server from 10 to 12.

Does the PAF support PG 12 or any docs can help on this?

Appreciate!!

**Comment by ioguix** [comment]
Hello,

Yes, PAF supports PostgreSQL 12. We have a quick start with CentOS 8 using pgsql 12: http://clusterlabs.github.io/PAF/Quick_Start-CentOS-8.html

We don't provide docs about how to do a major upgrade of PostgreSQL. PostgreSQL community is full of resources about this.

Considering the Pacemaker part of the upgrade, either you build a full new cluster on new servers, or you add new resources to control your new pgsql 12 instances in the same cluster. If you are doing an inplace upgrade, put the cluster in maintenance mode, and update the existing resources with the parameters you need to change.

No matter what, exercise first and write a procedure in a devel environment. Do not hesitate to ask question here if needed.

Regards,

**Comment by dashng** [comment]
@ioguix  
I update the PAF with the command below:

```
rpm -ivh resource-agents-paf-2.3.0-1.noarch.rpm --nodeps
```

then follow the guide to add the resource:

```
# pgsqld
pcs -f cluster1.xml resource create pgsqld ocf:heartbeat:pgsqlms \
    bindir=/usr/pgsql-12/bin pgdata=/var/lib/pgsql/12/data       \
    op start timeout=60s                                         \
    op stop timeout=60s                                          \
    op promote timeout=30s                                       \
    op demote timeout=120s                                       \
    op monitor interval=15s timeout=10s role="Master"            \
    op monitor interval=16s timeout=10s role="Slave"             \
    op notify timeout=60s                                        \
    promotable notify=true
```

The error occured below:

```
Error: invalid resource operation option 'notify', allowed options are: OCF_CHECK_LEVEL, description, enabled, id, interval, interval-origin, name, on-fail, record-pending, requires, role, start-delay, timeout
Error: 'promotable' is not a valid operation name value, use demote, meta-data, methods, monitor, monitor, monitor, notify, promote, reload, start, stop, validate-all, use --force to override
```

I try to install pg 12 PAF on centos7. 

Appreciate if any comments. thanks.

**Comment by ioguix** [comment]
Hi,

You are not supposed to upgrade your Pacemaker setup, only your PostgreSQL one. The doc I linked was just to adapt to suit your case in regard with your PostgreSQL upgrade.

Pacemaker setup is different between centos7 and centos8, partly because pcs evolved. This is why you have this error.

The differences between setup of PostgreSQL <12 and PostgreSQL 12 is documented in our official doc: https://clusterlabs.github.io/PAF/configuration.html

Regards,

**Comment by dashng** [comment]
```
Cluster name: rediscluster

WARNINGS:
Corosync and pacemaker node names do not match (IPs used in setup?)

Stack: corosync
Current DC: ui-dalian-ued2 (version 1.1.21-4.el7-f14e36fd43) - partition with quorum
Last updated: Mon Aug  3 09:56:29 2020
Last change: Mon Aug  3 09:29:26 2020 by hacluster via crmd on ui-dalian-ued2

2 nodes configured
3 resources configured

              *** Resource management is DISABLED ***
  The cluster will not attempt to start, stop or recover services

Online: [ ui-dalian-ued ui-dalian-ued2 ]

Full list of resources:

 Master/Slave Set: pgsql-ha [pgsqld] (unmanaged)
     Stopped: [ ui-dalian-ued ui-dalian-ued2 ]
 pgsql-master-ip	(ocf::heartbeat:IPaddr2):	Stopped (unmanaged)

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/disabled
```
Following the guide and after the configuration, the status is unmanaged.

**Comment by dashng** [comment]
'pcs property unset maintenance-mode' resoved.
