### ISSUE TITLE
Geo-Cluster questions

### ISSUE THREAD

**Issue by Orsopepe** [ClusterLabs/PAF#175]
Hi Guys,

I was asked to build a geographic cluster with automatic failover that replicates on 3 server rooms located on the same country.
the internet that connects them is 100mb/s.
I immediately discarded the Patroni cluster as too sensitive to network latencies and network speeds.
I know that PAF supports Geo Replication but I havent found any kind of information about it.

Thanks for your support

Pepe

**Comment by ioguix** [comment]
Hi @Orsopepe,

The latency here will be the main issue for both PostgreSQL replication and Corosync.

I don't have experience or documentation in regard to geo clusters. However, I've seen various discussions related to them on Pacemaker user mailing list. It is usually about increasing some timeouts in corosync configuration and/or setting up Booth: https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html/Pacemaker_Explained/ch15.html

Regards,

**Comment by ioguix** [comment]
PS: do not hesitate to report here the result of your research!

**Comment by Orsopepe** [comment]
Sorry for the late answer, i will let you know any kind of solution im going to test!
thanks!

**Comment by YanChii** [comment]
Hi @Orsopepe 

I know I'm quite late to the party but I've done geo patches to PAF some time ago as I've been also designing the geo-ha: https://github.com/YanChii/PAF/tree/master-geo-ha
I didn't merge the latest PAF development there but maybe you will find inspiration in it. The main thing is to not rely on fencing and work with quorum loss.
Related issues: #59, #57 

Jan
