### ISSUE TITLE
The output of the command 'crm_mon -1' is different from PG 10 Cluster.

### ISSUE THREAD

**Issue by dashng** [ClusterLabs/PAF#177]
I setup the PG12 PAF cluster successfully, but the command 'crm_mon -Afr -1' ouput is far different from the PG10 version.

For the PG10 version, the output provide like 'HA:sync' to identicate if the replication working well.

Why for the PG12, the message disappeared, is there anything wrong for my cluster?
The ouput of PG 12:
![image](https://user-images.githubusercontent.com/13565116/89241016-55886d80-d630-11ea-9960-03422a5e5e32.png)
The output of PG10:
![image](https://user-images.githubusercontent.com/13565116/89241376-45bd5900-d631-11ea-9a7a-edf287487425.png)

**Comment by dashng** [comment]
@ioguix any comments on this? Appreciate.

**Comment by blogh** [comment]
Hi,

I think you are not using the same resource agent anymore.
There is another resource agent for postgresql (pgsql [1]). That resource agent has the info you are talking about : data-status, master-baseline etc.. 

PAF (pgsqlms) doesn't have them.

Blogh.

[1] https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/pgsql

**Comment by dashng** [comment]
Thanks @blogh, then which one is better?

**Comment by ioguix** [comment]
> which one is better?

This has been answered here and there in the past. Maybe in an issue here, on the Pacemaker mailing list, etc.

There's at least one entry in the FAQ: https://clusterlabs.github.io/PAF/FAQ.html#why-new-ra-for-postgresql

As developers of PAF, we are biased, obviously.

**Comment by dashng** [comment]
@ioguix Thanks a lot.
