### ISSUE TITLE
Unexpected state for instance "pgsqld" (returned 9) ] after emergency shutdown master node

### ISSUE THREAD

**Issue by VladimirSevero** [ClusterLabs/PAF#181]
Problem restoring the cluster after a simulated "reboot-n -ff -d"crash. After an emergency shutdown of a node that is in the master state, pgsqlms promotes the node that was in the Slave to Master. After the disabled node returns, it returns to the master state and tries to start pgsqld in master mode, but after several attempts it crashes with the error Unexpected state for instance "pgsqld" (returned 9) ].

log:
Oct 21 19:30:00 msk-ad04-db07 systemd[1]: Started Crash recovery kernel arming.
Oct 21 19:30:00 msk-ad04-db07 systemd[1]: Startup finished in 1.776s (kernel) + 2.386s (initrd) + 6.478s (userspace) = 10.642s.
Oct 21 19:30:00 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of probe operation for virtual_ip_master on msk-ad04-db07: 7 (not running)
Oct 21 19:30:00 msk-ad04-db07 sssd[nss][1235]: Enumeration requested but not enabled
Oct 21 19:30:00 msk-ad04-db07 pgsqlms(pgsqld)[1829]: ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
Oct 21 19:30:00 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_monitor_0:1829:stderr [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
Oct 21 19:30:00 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of probe operation for pgsqld on msk-ad04-db07: 9 (master (failed))
Oct 21 19:30:00 msk-ad04-db07 pacemaker-controld[1449]: notice: msk-ad04-db07-pgsqld_monitor_0:6 [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed\n ]
Oct 21 19:30:01 msk-ad04-db07 pgsqlms(pgsqld)[1898]: ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
Oct 21 19:30:01 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_notify_0:1898:stderr [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
Oct 21 19:30:01 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of notify operation for pgsqld on msk-ad04-db07: 0 (ok)
Oct 21 19:30:01 msk-ad04-db07 pgsqlms(pgsqld)[1916]: ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
Oct 21 19:30:01 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_demote_0:1916:stderr [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
Oct 21 19:30:01 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of demote operation for pgsqld on msk-ad04-db07: 1 (error)
Oct 21 19:30:01 msk-ad04-db07 pacemaker-controld[1449]: notice: msk-ad04-db07-pgsqld_demote_0:12 [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed\n ]
Oct 21 19:30:01 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting fail-count-pgsqld#demote_0[msk-ad04-db07]: (unset) -> 1
Oct 21 19:30:01 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting last-failure-pgsqld#demote_0[msk-ad04-db07]: (unset) -> 1603297800
Oct 21 19:30:01 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of notify operation for pgsqld on msk-ad04-db07: 0 (ok)
Oct 21 19:30:01 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of notify operation for pgsqld on msk-ad04-db07: 0 (ok)
Oct 21 19:30:01 msk-ad04-db07 pgsqlms(pgsqld)[1962]: ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
Oct 21 19:30:01 msk-ad04-db07 pgsqlms(pgsqld)[1962]: ERROR: Unexpected state for instance "pgsqld" (returned 9)
Oct 21 19:30:01 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_stop_0:1962:stderr [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
Oct 21 19:30:01 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_stop_0:1962:stderr [ ocf-exit-reason:Unexpected state for instance "pgsqld" (returned 9) ]
Oct 21 19:30:01 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of stop operation for pgsqld on msk-ad04-db07: 1 (error)
Oct 21 19:30:01 msk-ad04-db07 pacemaker-controld[1449]: notice: msk-ad04-db07-pgsqld_stop_0:15 [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed\nocf-exit-reason:Unexpected state for instance "pgsqld" (returned 9)\n ]
Oct 21 19:30:01 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting fail-count-pgsqld#stop_0[msk-ad04-db07]: (unset) -> INFINITY
Oct 21 19:30:01 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting last-failure-pgsqld#stop_0[msk-ad04-db07]: (unset) -> 1603297801
Oct 21 19:30:19 msk-ad04-db07 corosync[1282]:  [KNET  ] pmtud: PMTUD link change for host: 2 link: 0 from 469 to 1397
Oct 21 19:30:19 msk-ad04-db07 corosync[1282]:  [KNET  ] pmtud: Global data MTU changed to: 1397
Oct 21 19:30:54 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting fail-count-pgsqld#demote_0[msk-ad04-db07]: 1 -> (unset)
Oct 21 19:30:54 msk-ad04-db07 pacemaker-controld[1449]: notice: Forcing the status of all resources to be redetected
Oct 21 19:30:54 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting fail-count-pgsqld#stop_0[msk-ad04-db07]: INFINITY -> (unset)
Oct 21 19:30:54 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting last-failure-pgsqld#stop_0[msk-ad04-db07]: 1603297801 -> (unset)
Oct 21 19:30:54 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting last-failure-pgsqld#demote_0[msk-ad04-db07]: 1603297800 -> (unset)
Oct 21 19:30:54 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of probe operation for virtual_ip_master on msk-ad04-db07: 7 (not running)
Oct 21 19:30:54 msk-ad04-db07 pgsqlms(pgsqld)[2042]: ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
Oct 21 19:30:54 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_monitor_0:2042:stderr [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
Oct 21 19:30:54 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of probe operation for pgsqld on msk-ad04-db07: 9 (master (failed))
Oct 21 19:30:54 msk-ad04-db07 pacemaker-controld[1449]: notice: msk-ad04-db07-pgsqld_monitor_0:22 [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed\n ]
Oct 21 19:30:55 msk-ad04-db07 pgsqlms(pgsqld)[2104]: ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
Oct 21 19:30:55 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_notify_0:2104:stderr [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
Oct 21 19:30:55 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of notify operation for pgsqld on msk-ad04-db07: 0 (ok)
Oct 21 19:30:55 msk-ad04-db07 pgsqlms(pgsqld)[2122]: ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
Oct 21 19:30:55 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_demote_0:2122:stderr [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
Oct 21 19:30:55 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of demote operation for pgsqld on msk-ad04-db07: 1 (error)
Oct 21 19:30:55 msk-ad04-db07 pacemaker-controld[1449]: notice: msk-ad04-db07-pgsqld_demote_0:28 [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed\n ]
Oct 21 19:30:55 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting fail-count-pgsqld#demote_0[msk-ad04-db07]: (unset) -> 1
Oct 21 19:30:55 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting last-failure-pgsqld#demote_0[msk-ad04-db07]: (unset) -> 1603297854
Oct 21 19:30:55 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of notify operation for pgsqld on msk-ad04-db07: 0 (ok)
Oct 21 19:30:55 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of notify operation for pgsqld on msk-ad04-db07: 0 (ok)
Oct 21 19:30:55 msk-ad04-db07 pgsqlms(pgsqld)[2168]: ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
Oct 21 19:30:55 msk-ad04-db07 pgsqlms(pgsqld)[2168]: ERROR: Unexpected state for instance "pgsqld" (returned 9)
Oct 21 19:30:55 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_stop_0:2168:stderr [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
Oct 21 19:30:55 msk-ad04-db07 pacemaker-execd[1445]: notice: pgsqld_stop_0:2168:stderr [ ocf-exit-reason:Unexpected state for instance "pgsqld" (returned 9) ]
Oct 21 19:30:55 msk-ad04-db07 pacemaker-controld[1449]: notice: Result of stop operation for pgsqld on msk-ad04-db07: 1 (error)
Oct 21 19:30:55 msk-ad04-db07 pacemaker-controld[1449]: notice: msk-ad04-db07-pgsqld_stop_0:31 [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed\nocf-exit-reason:Unexpected state for instance "pgsqld" (returned 9)\n ]
Oct 21 19:30:55 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting fail-count-pgsqld#stop_0[msk-ad04-db07]: (unset) -> INFINITY
Oct 21 19:30:55 msk-ad04-db07 pacemaker-attrd[1447]: notice: Setting last-failure-pgsqld#stop_0[msk-ad04-db07]: (unset) -> 1603297855

**Comment by ioguix** [comment]
Hi,

Please, read the FAQ : https://clusterlabs.github.io/PAF/FAQ.html#how-to-failback
Which redirect to: https://clusterlabs.github.io/PAF/administration.html#failover

Regards,
