### ISSUE TITLE
Failed Resource Actions

### ISSUE THREAD

**Issue by ykdhan** [ClusterLabs/PAF#183]
I got this error after following the tutorial.
Except, I skipped fencing. I did not implement fencing.
Do I have to? Also, the parameter 'primary_conninfo' is already set to 'host=PG_VIP application_name=MASTER_HOSTNAME'.
I don't know why it keeps printing that error.

```
[root@zbx-db1 ~]# pcs status
Cluster name: zabbixdb
Stack: corosync
Current DC: zbx-db2 (version 1.1.23-1.el7_9.1-9acf116022) - partition with quorum
Last updated: Mon Dec 28 11:50:46 2020
Last change: Mon Dec 28 11:42:44 2020 by root via cibadmin on zbx-db1

2 nodes configured
3 resource instances configured (2 BLOCKED from further action due to failure)

Online: [ zbx-db1 zbx-db2 ]

Full list of resources:

 Master/Slave Set: pgsql-ha [pgsqld]
     pgsqld     (ocf::heartbeat:pgsqlms):       FAILED zbx-db2 (Monitoring, blocked)
     pgsqld     (ocf::heartbeat:pgsqlms):       FAILED zbx-db1 (Monitoring, blocked)
 pgsql-ip       (ocf::heartbeat:IPaddr2):       Stopped

Failed Resource Actions:
* pgsqld_stop_0 on zbx-db2 'invalid parameter' (2): call=14, status=complete, exitreason='Parameter "primary_conninfo" MUST contain 'application_name=zbx-db2'. It is currently set to 'host=192.168.56.30 application_nam',
    last-rc-change='Mon Dec 28 11:40:55 2020', queued=0ms, exec=137ms
* pgsqld_stop_0 on zbx-db1 'invalid parameter' (2): call=14, status=complete, exitreason='Parameter "primary_conninfo" MUST contain 'application_name=zbx-db1'. It is currently set to 'host=192.168.56.30 application_nam',
    last-rc-change='Mon Dec 28 11:40:55 2020', queued=0ms, exec=251ms

Daemon Status:
  corosync: active/disabled
  pacemaker: inactive/disabled
  pcsd: active/enabled
```

**Comment by ykdhan** [comment]
Typo

**Comment by ioguix** [comment]
Hi,

I suppose you found your error as you closed the issue.

Note however that you MUST set up fencing in production.

There's no real good reason to do some personal quick and dirty tests without fencing, but if you do, you'll have to monitor all you cluster logs and fence by hand when the cluster requires it, using: `pcs stonith confirm <node name>`..

See: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/high_availability_add-on_reference/s1-fencedevicemanage-haar

Without fencing, either the cluster will refuse to auto-failover your primary pgsql, or you will split brain your cluster with bad configurations while forcing it to failover.
