### ISSUE TITLE
How to change master node in pacemaker. 

### ISSUE THREAD

**Issue by karippery** [ClusterLabs/PAF#184]
I setup pacemaker  postgresql synchronization. 

And for testing I reboot the master(server1). so now my client(server2, server3) become master. 
 

![testing+](https://user-images.githubusercontent.com/33422429/103645671-ad692e80-4f58-11eb-90eb-397195e54fa1.PNG)

**Now I need to maker server1  to be master. How can I do that?**  I thought it will do automatically 

And I notice on postgresql status some changes , missing one server.

![psqltesting](https://user-images.githubusercontent.com/33422429/103645983-31bbb180-4f59-11eb-9147-19bb3bed9eee.PNG)

Please help me

**Comment by ioguix** [comment]
Hi,

> Now I need to maker server1 to be master. How can I do that?

I'm sure one of the available administration cookbook from https://clusterlabs.github.io/PAF/documentation.html might answer your question.

> I thought it will do automatically

No, by default there's no constraint designating a preferred node for the primary location.

Make sure to train yourself on Pacemaker internals, mechanism and setup. You should plan to admin, improve and fix.

Regards,
