### ISSUE TITLE
slave not promoted in case of no free disk space available on master node

### ISSUE THREAD

**Issue by angeloior** [ClusterLabs/PAF#188]
Hi PAF,
I'm a novice making my first PAF CentOS7 cluster, I'm looking for help.
My cluster is composed by two virtual nodes, without fencing devices.
I noticed that in case of the master node is running out of disk space the cluster does not failover  on slave node.
Failover is performing perfectly while in case of rebooting the node instead.
The root cause is that pacemaker is not able to stop correctly the postgresql (v10) process.
Which is now the best way to manage this problem ?
Thank you very much.

**Comment by ioguix** [comment]
Hi,

Here the doc: https://clusterlabs.github.io/PAF/CentOS-7-admin-cookbook.html#setting-up-a-watchdog
