### ISSUE TITLE
Pacemaker can not promote master

### ISSUE THREAD

**Issue by mekaam** [ClusterLabs/PAF#189]
Hi Experts,
First thanks for all your efforts and generous help.
I am trying to setup Postgres 12 with Pacemaker on Oracle Linux 7 but both nodes are marked slaves
[root@dbnode2 heartbeat]# pcs status
Cluster name: cluster_pgsql
Stack: corosync
Current DC: dbnode2 (version 1.1.23-1.0.1.el7-9acf116022) - partition with quorum
Last updated: Sat Apr  3 18:12:37 2021
Last change: Sat Apr  3 18:09:40 2021 by root via crm_resource on dbnode2

2 nodes configured
4 resource instances configured

Online: [ dbnode1 dbnode2 ]

Full list of resources:

 dummy_service  (ocf::pacemaker:Dummy): Started dbnode1
 Cluster_VIP    (ocf::heartbeat:IPaddr2):       Started dbnode1
 Master/Slave Set: pgsql-ha-master [pgsql-ha]
     Slaves: [ dbnode1 dbnode2 ]

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/enabled
[root@dbnode2 heartbeat]#

[root@dbnode2 heartbeat]# corosync -version
Corosync Cluster Engine, version '2.4.5'
Copyright (c) 2006-2009 Red Hat, Inc.

[root@dbnode2 heartbeat]#  pacemakerd -$
Pacemaker 1.1.23-1.0.1.el7
Written by Andrew Beekhof

May you please help 
Thanks

**Comment by ioguix** [comment]
Hi,

We lack a lot of details.

Does your PostgreSQL instances were replicating correctly before being assimilated in Pacemaker?
Did you stopped them gracefully before creating the Pacemaker resources?
What is your cluster configuration?
What are the current promotion scores in the cluster?

If your cluster is clean and everything is safely configured, maybe you can just set a small promotion score  (eg. 1) on a node, Pacemaker will then take care of everything else: promote the instance, setup correct scores, etc.

**Comment by mekaam** [comment]
Good day,
I do sincerely apologize for the delay response i was not well.
thank you for your help, indeed it was issue with presetup replication not done correctly
now it is working as documented.
really appreciate you support.
