### ISSUE TITLE
When kill postgres (postmaster) process and cannot promote on Slave

### ISSUE THREAD

**Issue by ashurei** [ClusterLabs/PAF#191]
I have completed cluster configuration with PAF guide,
so when I perform 'pcs cluster stop' or 'pcs cluster standby'
I can see that the cluster is failed over to slave node.

I think that when postgres main process is killed suddenly the cluster will be failed over to slave node.
But in this situation, the postgres try to promote on slave node and fail.
And then the postgres go back to old primary and restart with primary mode.

After I check the 'pgsqlms' and figure out the point.
```
[root]# vi /usr/lib/ocf/resource.d/heartbeat/pgsqlms
sub _confirm_stopped {
...
    if ( $controldata_rc == $OCF_RUNNING_MASTER ) {
        # The controldata has not been updated to "shutdown".
        # It should mean we had a crash on a primary instance.
        ocf_exit_reason(
            'Instance "%s" controldata indicates a running primary instance, the instance has probably crashed',
            $OCF_RESOURCE_INSTANCE );
        return $OCF_FAILED_MASTER;
```

When the postgres is killed suddenly the status in pg_controldata is 'in production'.
So the postgres cannot promote on slave node.

I changed the return value as below and I obtained the result what I want.
```
#return $OCF_FAILED_MASTER;
return $OCF_NOT_RUNNING;`
```
I was wondering that why you created this function like this.

**Comment by blogh** [comment]
Hi, 

When PostgreSQL goes down on the master node, Pacemaker will try to restart it on the same node first if the node is still available. I don't understand what you re explaining about the standby. It would be very helpful is you could send the pacemaker logs on both nodes to understand the situation better.

`_confirm_stopped` is used only when the instance was reported as unavailable by pg_isready (rc 2): 
* https://github.com/ClusterLabs/PAF/blob/d5b3e6d6417300edf9403219c00140a2a840c64c/script/pgsqlms#L1639
* https://github.com/ClusterLabs/PAF/blob/d5b3e6d6417300edf9403219c00140a2a840c64c/script/pgsqlms#L1664

In this function, we check if there is a process related to the pidfile. If not we continue and after a few other tests we check the control file. At this point if the instance is reported as RUNNING here, the only possible outcome is that it crashed.
Therefore we set the return code to `$OCF_FAILED_MASTER`.

Benoit
