### ISSUE TITLE
Does this version of PAF run with PostgreSQL 13?

### ISSUE THREAD

**Issue by dumm1** [ClusterLabs/PAF#192]
I setup a set of PostgreSQL with stream replication.
The resources have be created while it indicated "0 nodes configured"
When I configure the HA for PG12 with the same process, the nodes were added successfully.
Did I miss important steps for the HA configuration with PG13?

~~~
#########################################################
0 nodes configured
3 resource instances configured


Full list of resources:

 pgsqld (ocf::heartbeat:pgsqlms):       Stopped
 Resource Group: master-group
     pgsql-master-ip    (ocf::heartbeat:IPaddr2):       Stopped
 Resource Group: slave-group
     pgsql-slavor-ip    (ocf::heartbeat:IPaddr2):       Stopped

Node Attributes:

Migration Summary:
#########################################################
~~~

(Please ignore the typos)

By the way, does postgresql-13 service need stopping before launch the HA resources?

**Comment by ioguix** [comment]
> The resources have be created while it indicated "0 nodes configured"

This seems impossible to me. You must have at least one node to be able to add any resource to the live CIB.

Or maybe you are adding resource using an offline/shadow CIB using pcs or crmsh? Do you have the environment variable `CIB_shadow` set?
How did you end up in this situation?

> When I configure the HA for PG12 with the same process, the nodes were added successfully.

You might have some slightly differents environments or commands.

> Did I miss important steps for the HA configuration with PG13?

No, there's no difference between pg12 and pg13 in regard to PAF.

**Comment by emeygret** [comment]
Hello, I followed quick start with Debian 10(on Ubuntu 20.04 and pgdg repo) and same issue for me, pg12 is working fine but pg13 is not working.
