### ISSUE TITLE
Can I add replica(sl*ve) resource in pgsqld?

### ISSUE THREAD

**Issue by dumm1** [ClusterLabs/PAF#193]
Previously, a virtual ip for read-only purpose could be add in the pgsql resource.
Is it possible to add such a virtual IP in current PAF version?

**Comment by ioguix** [comment]
Hi,

I'm not sure I understand your question. PAF doesn't handle vIP itself. The cluster does, using colocation and orders rules.

This is not related to the PAF version, at all.

> Is it possible to add such a virtual IP in current PAF version?

Yes...
