### ISSUE TITLE
PCS/pacemaker recent updates "broke" PAF(?)

### ISSUE THREAD

**Issue by lejeczek** [ClusterLabs/PAF#194]
Hi guys.
I've had a working PAF on a small cluster which was problem free until recent updates of OS packages.
I'm on CentOS Stream with these (maybe more) recently updated:
corosynclib-3.1.0-5.el8.x86_64
pacemaker-schemas-2.1.0-2.el8.noarch
pacemaker-cluster-libs-2.1.0-2.el8.x86_64
pacemaker-cli-2.1.0-2.el8.x86_64
pacemaker-libs-2.1.0-2.el8.x86_64
resource-agents-paf-2.3.0-1.noarch
pacemaker-2.1.0-2.el8.x86_64
resource-agents-4.1.1-96.el8.x86_64
corosync-3.1.0-5.el8.x86_64
pcs-0.10.8-2.el8.x86_64 

which all in all should make it easily reproducible.
It's not only PAF resource which had already existed (prior to updates) that broke, but also creation of a new resource fails, in a way that pcs/PAF cannot start master/slave.

many thanks, L

**Comment by khattori** [comment]
I have encountered the same problem.
I think the problem is caused by a slight change in the behavior of the crm_master command between pacemaker 2.0.5 and 2.1.0.

pacemaker-2.0.5:
```
# crm_master --lifetime forever --quiet --get-value -r res_pgsql
1001
```
pacemaker-2.1.0:
```
# crm_master --lifetime forever --get-value -r res_pgsql
crm_attribute: Missing argument for --get-value
```

**Comment by lejeczek** [comment]
Proposed fix does not seem to work for me.
From what PCS says, to me it seems, it is not happy with "monitor"

Failed Resource Actions:
  * pgsqld_monitor_15000 on c8kubernode1 'error' (1): call=246, status='Timed Out', exitreason='', last-rc-change='2021-07-05 12:25:17 +01:00', queued=0ms, exec=10001ms

Seems that master is chosen and started then slave(s) but very quickly resource begins to reshuffle cluster for that reason above, I suppose.

many thanks, Ll

**Comment by ioguix** [comment]
Hi guys,

Thank you for the report.

I am able to reproduce this issue on my side.

It seems `crm_attribute` or `crm_master` doesn't support negative score anymore. It looks like a pacemaker regression:

~~~console
# OCF_RESOURCE_INSTANCE=pgsqld crm_attribute --quiet --lifetime forever --promotion --node "srv1" --update "-1000"
crm_attribute: Unknown option -0

# OCF_RESOURCE_INSTANCE=pgsqld crm_master --quiet --lifetime forever --node "srv1" --update "-1000"
crm_attribute: Unknown option -0
~~~

I'll try to investigate further how we are supposed to set negative score on the pacemaker side.

For the record, I filled a bug report on pacemaker side: https://bugs.clusterlabs.org/show_bug.cgi?id=5480
Hopefully I'm wrong and this will be an easy fix on PAF side.

Regards,

**Comment by lejeczek** [comment]
gee man... 22 days later :)
thanks, L

**Comment by ioguix** [comment]
> gee man... 22 days later :)

I'm not sure how to deal with this answer.

But anyway, waiting for pacemaker devs now...

**Comment by lejeczek** [comment]
probably the the way of the proverb's - better late than never.
Certainly I, and others too I presume, are grateful and happy that author has noticed and looking into it.

**Comment by ioguix** [comment]
Hi,

The bugs has been fixed upstream: https://bugs.clusterlabs.org/show_bug.cgi?id=5480#c3. 

I suppose a new release of Pacemaker is coming soon.

**Comment by ioguix** [comment]
Hi there,

I've been testing Pacemaker 2.1.1 rc3 today en centos 8 stream:

~~~
pacemaker-libs-2.1.1-0.1.rc3.el8.x86_64
pacemaker-schemas-2.1.1-0.1.rc3.el8.noarch
pacemaker-cluster-libs-2.1.1-0.1.rc3.el8.x86_64
pacemaker-2.1.1-0.1.rc3.el8.x86_64
pacemaker-cli-2.1.1-0.1.rc3.el8.x86_64
~~~

Everything works correctly with version 2.3 of PAF.
