### ISSUE TITLE
Compatibility with Postgresql version 13

### ISSUE THREAD

**Issue by tonydasilv** [ClusterLabs/PAF#200]
Hello Team,
Could you confim that the latest verison of PAF (2.3.0) support the lastest release of postgrsql version 13 ?

Thanks

**Comment by ioguix** [comment]
Hello,

As wrote in some past issues, there's not difference between 12 and 13 in regard to PAF.

**Comment by tonydasilv** [comment]
Hi ioguix,

Thanks for your feedback.
