### ISSUE TITLE
Cluster with 3 nodes , 3rd node in different network

### ISSUE THREAD

**Issue by LucaGalvagno** [ClusterLabs/PAF#202]
Hi [ioguix](https://github.com/ioguix),
I have the need of having a cluster with 3 nodes, but 2 nodes are in a network (main site) and the 3rd one is running in another network (emergency site) . Obviously access the emergency site through VIP when is master is objectively impossible, but is a non problem. In our case t the apps connecting to postgres in the emergency site are using the emergency site postgres ip and are not functioning when the main site is up.

My question is how does behave PAF in such case ? It would do the promotion anyway ?
Another problem is how would function the primary_conninfo param in such case ?

Thanks
Kind Regards

**Comment by ioguix** [comment]
Hi,

> My question is how does behave PAF in such case ? It would do the promotion anyway ?

I suppose you don't want to failover to the remote site. Moreover, spanning Pacemaker between remote sites add more constraints and requires some more attentions. Just keep alone out of the cluster.

> Another problem is how would function the primary_conninfo param in such case ?

It really depend on your network and architecture...Why the emergency site cannot objectively access the VIP? How the site are interconnected?
