### ISSUE TITLE
problem during installation on almalinux 8.5 using postgres13

### ISSUE THREAD

**Issue by Orsopepe** [ClusterLabs/PAF#211]
Hi guys,

im trying to install the cluster on almalinux 8.5 using postgres13.
im using the usual recipe, unfortunately i encontered some problem.
when i fire up the cluster i got the following error:

~~~
Full List of Resources:
  * Clone Set: pgsqld-clone [pgsqld] (promotable):
    * pgsqld    (ocf::heartbeat:pgsqlms):        FAILED lta-alma-db3
    * pgsqld    (ocf::heartbeat:pgsqlms):        FAILED lta-alma-db2
    * Stopped: [ lta-alma-db1 ]
  * pgsql-master-ip     (ocf::heartbeat:IPaddr2):        Stopped

Failed Resource Actions:
  * pgsqld_stop_0 on lta-alma-db3 'invalid parameter' (2): call=12, status='complete', exitreason='Parameter "primary_conninfo" MUST contain 'application_name=lta-alma-db3'. It is currently s
et to 'user=repuser passfile='/var/l', last-rc-change='2022-04-29 10:56:40 -04:00', queued=0ms, exec=105ms
  * pgsqld_stop_0 on lta-alma-db2 'invalid parameter' (2): call=12, status='complete', exitreason='Parameter "primary_conninfo" MUST contain 'application_name=lta-alma-db2'. It is currently s
et to 'user=repuser passfile='/var/l', last-rc-change='2022-04-29 10:56:40 -04:00', queued=0ms, exec=100ms

Pending Fencing Actions:
  * reboot of lta-alma-db3 pending: client=pacemaker-controld.311164, origin=lta-alma-db1
  * reboot of lta-alma-db2 pending: client=pacemaker-controld.311164, origin=lta-alma-db1
~~~

all the servers are configured like that with the needed changes for each node on the `application_name`

~~~
#Replica connection Info
primary_conninfo = 'host=172.30.29.101 port=5432 user=repuser application_name=lta-alma-db2'
recovery_target_timeline = 'latest'
~~~

weird thing:

~~~
rpm -qa | grep paf
resource-agents-paf-4.1.1-98.el8_5.2.x86_64
~~~

its a release i dont know!

thanks for helpin!

Opepe

**Comment by Markus-** [comment]
Where did you configure the replication information? In pg 13 it is inside the db and not in a recovery.conf

Am 29.04.2022 um 17:02 schrieb Orsopepe ***@***.***>:

﻿

Hi guys,

im trying to install the cluster on almalinux 8.5 using postgres13.
im using the usual recipe, unfortunately i encontered some problem.
when i fire up the cluster i got the following error:

Full List of Resources:

  *   Clone Set: pgsqld-clone [pgsqld] (promotable):
     *   pgsqld (ocf:💓pgsqlms): FAILED lta-alma-db3
     *   pgsqld (ocf:💓pgsqlms): FAILED lta-alma-db2
     *   Stopped: [ lta-alma-db1 ]
  *   pgsql-master-ip (ocf:💓IPaddr2): Stopped

Failed Resource Actions:

  *   pgsqld_stop_0 on lta-alma-db3 'invalid parameter' (2): call=12, status='complete', exitreason='Parameter "primary_conninfo" MUST contain 'application_name=lta-alma-db3'. It is currently s
et to 'user=repuser passfile='/var/l', last-rc-change='2022-04-29 10:56:40 -04:00', queued=0ms, exec=105ms
  *   pgsqld_stop_0 on lta-alma-db2 'invalid parameter' (2): call=12, status='complete', exitreason='Parameter "primary_conninfo" MUST contain 'application_name=lta-alma-db2'. It is currently s
et to 'user=repuser passfile='/var/l', last-rc-change='2022-04-29 10:56:40 -04:00', queued=0ms, exec=100ms

Pending Fencing Actions:

  *   reboot of lta-alma-db3 pending: client=pacemaker-controld.311164, origin=lta-alma-db1
  *   reboot of lta-alma-db2 pending: client=pacemaker-controld.311164, origin=lta-alma-db1

all the servers are configured like that with the needed changes for each node on the application_name

#Replica connection Info
primary_conninfo = 'host=172.30.29.101 port=5432 user=repuser application_name=lta-alma-db2'
recovery_target_timeline = 'latest'

weird thing:
rpm -qa | grep paf
resource-agents-paf-4.1.1-98.el8_5.2.x86_64

its a release i dont know!

thanks for helpin!

Opepe

**Comment by Orsopepe** [comment]
Hi,

thanks for answering

the replication information has been configured into postgres.conf, im i wrong?

thanks

Opepe

**Comment by ioguix** [comment]
> weird thing:
>
> ~~~
> rpm -qa | grep paf
> resource-agents-paf-4.1.1-98.el8_5.2.x86_64
> ~~~
>
> its a release i dont know!

See this following thread: https://lists.clusterlabs.org/pipermail/users/2022-February/030023.html

**Comment by ioguix** [comment]
Hi,

The error message is truncated from `pcs status`/`crm_mon`, you could find the full one in the log file.

However, I noticed the error message is reporting the current `primary_conninfo` start with:

~~~
'user=repuser passfile='/var/l'
~~~

Where you report setting it to eg.:

~~~
'host=172.30.29.101 port=5432 user=repuser application_name=lta-alma-db2'
~~~

Both values don't match. So somewhat, your `primary_conninfo` is overwritten somewhere on the road during the startup.

Check for config file inclusion or `postgresql.conf.auto` ?

**Comment by Orsopepe** [comment]
Hi, 

i figured out the postgresql.conf.auto was not alligned to the right configuration ('host=172.30.29.101 port=5432 user=repuser application_name=lta-alma-db2')

wiped the wrong configuration into postgresql.conf.auto and restarted the cluster everything works as expected!

thanks for helping Jehan-Guillaume!

it can be closed!
have a good day!

Opepe

**Comment by ioguix** [comment]
Have a good day as well!
