### ISSUE TITLE
Postgres start as slave in every severs

### ISSUE THREAD

**Issue by tatoruizlopez** [ClusterLabs/PAF#213]
Hello,

I've created the cluster using RH 7.9. And in every server postgres has started as slave:

[root@nodea centos]# pcs status
Cluster name: pgsql-HA
Stack: corosync
Current DC: nodeB (version 1.1.23-1.el7_9.1-9acf116022) - partition with quorum
Last updated: Wed Sep 14 18:29:29 2022
Last change: Wed Sep 14 18:09:55 2022 by root via crm_resource on nodeB

2 nodes configured
3 resource instances configured

Online: [ nodeA nodeB ]

Full list of resources:

 Master/Slave Set: pgsql-ha [pgsqld]
     Slaves: [ nodeA nodeB ]
 pgsql-pri-ip   (ocf::heartbeat:IPaddr2):       Stopped

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/disabled

Can you help me?

**Comment by tatoruizlopez** [comment]
Hi,

I've deleted the file recovery.conf and reboot the cluster and it's working. The issue know is with the auto-failover recover...

When I stop the Master the cluster doesn't switch to the other server

**Comment by ioguix** [comment]
Hi,

You should NOT remove recovery.conf by yourself. This is NOT a good solution.

I wonder why the cluster did not found the primary instance itself in the first place. After building your PgSQL replication and check everything worked, cleanly shutting down the standby then the primary is enough for the cluster to find who is where when it start.

Another solution is to set the promotion score by hand.

Did you setup and enabled fencing in your cluster? Did you read the logs? Anything useful?

Did you carefully read the whole documentation? Did it miss anything that could help you in your quest?
