### ISSUE TITLE
2 node cluster, when master node is shutdown, promotion of pgsqld on slave is aborted

### ISSUE THREAD

**Issue by themactech** [ClusterLabs/PAF#220]
I am in a test environment now, and when I shutdown my node currently running pgsqld as master, the slave node promotion is aborted with:

Failed Resource Actions:
  * pgsqld_promote_0 on cdrdbmaster 'error' (1): call=26, status='complete', exitreason='cdrdbslave is the best candidate to promote, aborting current promotion', last-rc-change='2023-02-25 02:50:05 -05:00', queued=0ms, exec=984ms
  
This occurs after cdrdbslave was shutting down...   And even after a few minutes of the cdrdbslave node being completely shutdown, the pgsqld resource was not promoted ever on the cdrdbmaster node.

Need to find out why a shutdown node gets voted best promotion candidate and stops the promotion to the surviving node.

When I restart the cdrdbslave node, it takes over pgsqld master role fine, and things are good

**Comment by ioguix** [comment]
Hi,

The promotion score are supplied by the primary node. So if you shutdown the standby and the primary, before the primary noticed the standby went away, the score will sit there forever.

You can set the score by hand using the `crm_attribute --promotion` or `crm_master` (deprecated) to trigger some changes if needed.

Regards,

**Comment by themactech** [comment]
That makes little sense to me, if an abrupt shutdown breaks the cluster, this means it will not survive a catastrophic hardware failure that immediately brings the master node down...  That seems like it defeats the purpose of a HA cluster.  I am rebuilding my setup (currently working on VM for testing), and will confirm if the failover-promotion works when the master node is put on standby.  If this works, then I will need to investigate if there are option to gracefully failover even in the case of the master node being put abruptly offline.

**Comment by themactech** [comment]
If the promotion score is the issue, that should not be in play in a 2-node cluster, or if a multi-node cluster has only 1 standby PostgreSQL node.  Could that not be verified first to determine if a promotion score query is even needed?  The corosync configuration has a special entry for a 2-node cluster (so quorum still works), does the PAF agent check for this?

**Comment by themactech** [comment]
Here are the results of my testing:

When initially configured, my cluster has the two following nodes:
-cdrdbmaster
-cdrdbslave

cdrdbmaster is the DC and runs the VirtualIP and is also master for pgsqld-clone

If I put the cdrdbmaster on standby with:

pcs node standby cdrdbmaster

then the cdrdbslave becomes DC, and properly takes over the Virtual IP, and get pgsqld promoted to master

If I then put the cdrdbmaster back online with:

pcs node unstandby cdrdbmaster

All services (and DC) stay on cdrdbslave (which is fine)

But then if I put the cdrdbslave on standby with:

pcs node standby cdrdbslave

The DC gets properly taken over by cdrdbmaster (so the cluster seem to operate fine) BUT the pgsqld service never promotes the pgsqld-clone on the master.  It stays in slave mode, and because of the colocation constraint, the VirtualIP resource is stopped.

When looking at the logs, I see the call to promote the pgsqld service on cdrdbslave (on my first standby test) and this being successful, but see no trace of a second promote command when setting the cdrdbslave on standby (when it was DC).  This is my pcs status at this point:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/4512548/221990809-6ab170fd-530b-4f79-8b57-6dca0f85f8b5.png">

**Comment by ioguix** [comment]
Hi,

Could you share the various scores on your cluster? The following commands should help:

* `crm_mon -frAno`
* `crm_simulate -sL`
* `pcs constraint list` and `pcs constraint show`

**Comment by ioguix** [comment]
> That makes little sense to me, if an abrupt shutdown breaks the cluster, this means it will not survive a catastrophic hardware failure that immediately brings the master node down... 

It does. 

You just created a scenario with a double failure scenario, moreover, with some obscure step I'm not sure to understand yet. So it's hard to explain why the cluster is acting like that.

BTW, How do you shutdown your nodes? I'm confused about this:

>  And even after a few minutes of the cdrdbslave node being completely shutdown, the pgsqld resource was not promoted ever on the cdrdbmaster node.

How a node could not be completely shutdown? What are you doing exactly? Maybe corosync is still up and running?

**Comment by themactech** [comment]
I should note that this shutdown test worked for all other Pacemaker clusters I have setup.  Slave node was properly promoted.  Starting it back up and then shutting down the newly promoted slave returned the original master to master.

I have done this with DRDB, Urbackup docker images, and a few other services.

**Comment by ioguix** [comment]
Hi,

> Following tests (if that had been successful), would have been to kill processes

Go ahead, kill processes...

I really would like to be able to reproduce. So please, provide a detailed procedure and versions of pacemaker, PAF, pgsql and OS.

Thanks,

**Comment by themactech** [comment]
Sorry for the delay.  I am currently writing a buildbook for this and also writing a script to automate the install.  So I would be able to give you very detailed build instructions and would also provide the version info you requested.  I would not however be able to post this in open forums.  Would I be able to get that to you by other means?  Once/if we solve this issue, I would gladly to a write-up in the forums for everyone's benefit.

**Comment by ioguix** [comment]
Isn't it possible to give simple instructions about how to reproduce?
Note that there's already some (old) vagrant scripts to provision a Pcmk/PAF cluster in few minutes in the `extra/` folder.
But anyway, can I reach you using your public email on your github account if you want to provide some private infos/script/buildbook?

**Comment by themactech** [comment]
Yes, you can reach me at themactech@me.com.

**Comment by ioguix** [comment]
Well, my email is rejected by your provider for non obvious reasons... sorry.

**Comment by themactech** [comment]
Could we connect via LinkedIn?

**Comment by ioguix** [comment]
Sorry, I still fail to understand why it's so complicated to describe step by step how to reproduce the issue...

**Comment by themactech** [comment]
Do I cover the entire PostgreSQL replication setup or just go from the Pacemaker cluster setup?  If you do not need the PostgreSQL replication setup I do then it would indeed be much shorter, and I would just include it in here.

**Comment by themactech** [comment]
I will have detailed steps and versions posted here by tomorrow.

**Comment by ioguix** [comment]
Unless your replication setup is really exotic, or if you want some advice about it, I don't need it...yet.

Thanks,

**Comment by themactech** [comment]
Going to be late this weekend or Monday, could not get that done today, and will have limited access over the weekend.

**Comment by themactech** [comment]
Sorry for not getting back sooner, but I was given other priorities, this project will be deployed without HA and a manual failover process will do (which is currently working).  Thank you for your input and your very generous offer of time/help.

**Comment by ioguix** [comment]
If your RTO/RPO allows manual failover, this is ALWAYS the best solution.

Regards,
