### ISSUE TITLE
How to configure PAF for two clusters from two different data centers

### ISSUE THREAD

**Issue by RajasekarArumugam28** [ClusterLabs/PAF#229]
Hi, 

I have 3 node (Master and 2 slave) setup in primary site and DR site. I have Pacemaker configure on both sites and I want to clarity how to configure replication between two data center masters. Please help.

**Comment by Markus-** [comment]
So you have a geo cluster using boothd or just two separate Clusters?

**Comment by RajasekarArumugam28** [comment]
Two separate clusters (below is the output of one of the cluster and we have same setup in another location)

Node List:
  * Online: [ pg0 pg1 pg2 ]

Full List of Resources:
  * MASTER	(ocf::pacemaker:Dummy):	 Started pg0
  * vip	(ocf::heartbeat:IPaddr2):	 Started pg0
  * mgmt_vip	(ocf::heartbeat:IPaddr2):	 Started pg0
  * Clone Set: pgsql-ha [pgsqld] (promotable):
    * Masters: [ pg0 ]
    * Slaves: [ pg1 pg2 ]

**Comment by RajasekarArumugam28** [comment]
Hi @Markus- any help is highly appreciated.

**Comment by Markus-** [comment]
If you have two different clusters, the PAF could not help. The PAF is used in one single PostgreSQL-Cluster.

**Comment by RajasekarArumugam28** [comment]
Hi @Markus- are you saying it is not possible to configure replication between two clusters with PAF

**Comment by Markus-** [comment]
This is not possible.

**Comment by ioguix** [comment]
Hi,

I'm not entirely sure it's not possible. You can probably setup a "promoted" cluster on one side and an "unpromoted" one on the other side using cascading replication.

You might be able to use `target-role` to keep your promotable resource as `unpromoted` on one side and set it to `promoted` on the other side, by hand. See: https://clusterlabs.org/pacemaker/doc/2.1/Pacemaker_Explained/singlehtml/#resource-meta-attributes

You might be able to use booth ticket as well, constraining the `promoted` role to a ticket.

The challenging part is how you setup the cascading replication so all node on the "unpromoted" side does not replicate from the "promoted" side but from a local standby...It might involve some pacemaker rules, or hand setup...

I never tried such setup, but it would be nice to experiment around this.

**Comment by RajasekarArumugam28** [comment]
I am trying on this and let you know if any queries.

**Comment by asphator** [comment]
I don't understand the point of having PAF between 2 masters of 2 different clusters... What do you failover then if not the master role ?
Could you describe a use case please ?
