### ISSUE TITLE
Node destroyed and rebuilded are not able to join the cluster 

### ISSUE THREAD

**Issue by RajasekarArumugam28** [ClusterLabs/PAF#231]
Hi Team,

We have destroyed the one of the node from our cluster and rebuilded the server back. Now I am trying to join the node back to the cluster as slave but it is not working.

I am trying to join the node pg1 back in cluster. tried crm_resource --cleanup --resource pgsqld, crm_resource --cleanup --node pg1 are not working. tried crm_simulate -SL --node-up pg1 as well to check.

pcs status
Cluster name: pg_cluster
Cluster Summary:
  * Stack: corosync
  * Current DC: pg2 (version 2.0.3-4b1f869f0f) - partition with quorum
  * Last updated: Wed May  1 10:30:52 2024
  * Last change:  Wed May  1 10:21:17 2024 by hacluster via crmd on pg1
  * 3 nodes configured
  * 6 resource instances configured (1 BLOCKED from further action due to failure)

Node List:
  * Online: [ pg0 pg1 pg2 ]

Full List of Resources:
  * MASTER	(ocf::pacemaker:Dummy):	 Started pg0
  * vip	(ocf::heartbeat:IPaddr2):	 Started pg0
  * mgmt_vip	(ocf::heartbeat:IPaddr2):	 Started pg0
  * Clone Set: pgsql-ha [pgsqld] (promotable):
    * pgsqld	(ocf::heartbeat:pgsqlms):	 FAILED pg1 (blocked)
    * Masters: [ pg0 ]
    * Slaves: [ pg2 ]

Failed Resource Actions:
  * pgsqld_stop_0 on pg1 'error' (1): call=71, status='complete', exitreason='Unexpected state for instance "pgsqld" (returned 9)', last-rc-change='2024-05-01 10:21:36Z', queued=0ms, exec=247ms

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/enabled

pcs log:

May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib/status/node_state[@id='1']/lrm[@id='1']/lrm_resources/lrm_resource[@id='mgmt_vip']/lrm_rsc_op[@id='mgmt_vip_monitor_10000']:  @transition-magic=0:0;10:16949:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228, @call-id=304, @rc-code=0, @op-status=0, @exec-time=68
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_process_request) 	info: Completed cib_modify operation for section status: OK (rc=0, origin=pg0/crmd/245, version=0.8173.59)
pgsqlms(pgsqld)[400526]:	May 01 10:21:36  ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_op_output) 	notice: pgsqld_notify_0[400526] error output [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_finished) 	info: finished - rsc:pgsqld action:notify call_id:67 pid:400526 exit-code:0 exec-time:238ms queue-time:0ms
May 01 10:21:36 pg1 pacemaker-controld  [399794] (process_lrm_event) 	notice: Result of notify operation for pgsqld on pg1: 0 (ok) | call=67 key=pgsqld_notify_0 confirmed=true cib-update=0
May 01 10:21:36 pg1 pacemaker-controld  [399794] (do_lrm_rsc_op) 	info: Performing key=20:16949:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228 op=pgsqld_demote_0
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_process_request) 	info: Forwarding cib_modify operation for section status to all (origin=local/crmd/58)
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_execute) 	info: executing - rsc:pgsqld action:demote call_id:68
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: --- 0.8173.59 2
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: +++ 0.8173.60 (null)
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib:  @num_updates=60
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib/status/node_state[@id='2']/lrm[@id='2']/lrm_resources/lrm_resource[@id='pgsqld']/lrm_rsc_op[@id='pgsqld_last_0']:  @operation_key=pgsqld_demote_0, @operation=demote, @transition-key=20:16949:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228, @transition-magic=-1:193;20:16949:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228, @exit-reason=, @call-id=-1, @rc-code=193, @op-status=-1, @last-rc-change=1714558896, @last-run=1714558896, @exec-time=0
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_process_request) 	info: Completed cib_modify operation for section status: OK (rc=0, origin=pg1/crmd/58, version=0.8173.60)
pgsqlms(pgsqld)[400547]:	May 01 10:21:36  ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_op_output) 	notice: pgsqld_demote_0[400547] error output [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed ]
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_finished) 	info: finished - rsc:pgsqld action:demote call_id:68 pid:400547 exit-code:1 exec-time:236ms queue-time:0ms
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_process_request) 	info: Forwarding cib_modify operation for section status to all (origin=local/crmd/59)
May 01 10:21:36 pg1 pacemaker-controld  [399794] (process_lrm_event) 	notice: Result of demote operation for pgsqld on pg1: 1 (error) | call=68 key=pgsqld_demote_0 confirmed=true cib-update=59
May 01 10:21:36 pg1 pacemaker-controld  [399794] (process_lrm_event) 	notice: pg1-pgsqld_demote_0:68 [ ocf-exit-reason:Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed\n ]
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: --- 0.8173.60 2
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: +++ 0.8173.61 (null)
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib:  @num_updates=61
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib/status/node_state[@id='2']/lrm[@id='2']/lrm_resources/lrm_resource[@id='pgsqld']/lrm_rsc_op[@id='pgsqld_last_0']:  @transition-magic=0:1;20:16949:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228, @exit-reason=Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed, @call-id=68, @rc-code=1, @op-status=0, @exec-time=236
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib/status/node_state[@id='2']/lrm[@id='2']/lrm_resources/lrm_resource[@id='pgsqld']/lrm_rsc_op[@id='pgsqld_last_failure_0']:  @operation_key=pgsqld_demote_0, @operation=demote, @transition-key=20:16949:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228, @transition-magic=0:1;20:16949:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228, @call-id=68, @rc-code=1, @last-rc-change=1714558896, @last-run=1714558896, @exec-time=236
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_process_request) 	info: Completed cib_modify operation for section status: OK (rc=0, origin=pg1/crmd/59, version=0.8173.61)
May 01 10:21:36 pg1 pacemaker-attrd     [399792] (attrd_peer_update) 	notice: Setting fail-count-pgsqld#demote_0[pg1]: (unset) -> 1 | from pg2
May 01 10:21:36 pg1 pacemaker-attrd     [399792] (attrd_peer_update) 	notice: Setting last-failure-pgsqld#demote_0[pg1]: (unset) -> 1714558896 | from pg2
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: --- 0.8173.61 2
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: +++ 0.8173.62 (null)
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib:  @num_updates=62
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: ++ /cib/status/node_state[@id='2']/transient_attributes[@id='2']/instance_attributes[@id='status-2']:  <nvpair id="status-2-fail-count-pgsqld.demote_0" name="fail-count-pgsqld#demote_0" value="1"/>
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_process_request) 	info: Completed cib_modify operation for section status: OK (rc=0, origin=pg2/attrd/87, version=0.8173.62)
May 01 10:21:36 pg1 pacemaker-controld  [399794] (do_lrm_rsc_op) 	info: Performing key=65:16949:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228 op=pgsqld_notify_0
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_execute) 	info: executing - rsc:pgsqld action:notify call_id:69
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: --- 0.8173.62 2
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: +++ 0.8173.63 (null)
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib:  @num_updates=63
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: ++ /cib/status/node_state[@id='2']/transient_attributes[@id='2']/instance_attributes[@id='status-2']:  <nvpair id="status-2-last-failure-pgsqld.demote_0" name="last-failure-pgsqld#demote_0" value="1714558896"/>
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_process_request) 	info: Completed cib_modify operation for section status: OK (rc=0, origin=pg2/attrd/88, version=0.8173.63)
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_finished) 	info: finished - rsc:pgsqld action:notify call_id:69 pid:400568 exit-code:0 exec-time:177ms queue-time:0ms
May 01 10:21:36 pg1 pacemaker-controld  [399794] (process_lrm_event) 	notice: Result of notify operation for pgsqld on pg1: 0 (ok) | call=69 key=pgsqld_notify_0 confirmed=true cib-update=0
May 01 10:21:36 pg1 pacemaker-controld  [399794] (do_lrm_rsc_op) 	info: Performing key=58:16950:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228 op=pgsqld_notify_0
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_execute) 	info: executing - rsc:pgsqld action:notify call_id:70
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_finished) 	info: finished - rsc:pgsqld action:notify call_id:70 pid:400584 exit-code:0 exec-time:197ms queue-time:0ms
May 01 10:21:36 pg1 pacemaker-controld  [399794] (process_lrm_event) 	notice: Result of notify operation for pgsqld on pg1: 0 (ok) | call=70 key=pgsqld_notify_0 confirmed=true cib-update=0
May 01 10:21:36 pg1 pacemaker-controld  [399794] (do_lrm_rsc_op) 	info: Performing key=4:16950:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228 op=pgsqld_stop_0
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_process_request) 	info: Forwarding cib_modify operation for section status to all (origin=local/crmd/60)
May 01 10:21:36 pg1 pacemaker-execd     [399791] (log_execute) 	info: executing - rsc:pgsqld action:stop call_id:71
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: --- 0.8173.63 2
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: Diff: +++ 0.8173.64 (null)
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib:  @num_updates=64
May 01 10:21:36 pg1 pacemaker-based     [399789] (cib_perform_op) 	info: +  /cib/status/node_state[@id='2']/lrm[@id='2']/lrm_resources/lrm_resource[@id='pgsqld']/lrm_rsc_op[@id='pgsqld_last_0']:  @operation_key=pgsqld_stop_0, @operation=stop, @transition-key=4:16950:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228, @transition-magic=-1:193;4:16950:0:b09c097a-da8a-4a1b-bd4c-910ef2bd3228, @exit-reason=, @call-id=-1, @rc-code=193, @op-status=-1, @exec-time=0

**Comment by RajasekarArumugam28** [comment]
@ioguix , do you have any idea how to join the node back to cluster after rebuild.

**Comment by ioguix** [comment]
Hi,

First, do you have a fencing method set up? At least watchdog enabled?

Then, it looks like you standby on `pg1` is not a standby. It says it is a running primary but doesn't answer to new sessions:

```
 ERROR: Instance "pgsqld" controldata indicates a running primary instance, the instance has probably crashed```
```

Make sure the instance on pg1 is a clean standby, stop it, then remove failcount on pg1.

**Comment by RajasekarArumugam28** [comment]
thanks @ioguix for the reply. We dont have any fencing or watchdog enabled. Usually when I start the node via pcs it will demote and start the slaves as standby. but now I am not sure how to remove the failcount and start the cluster via pcs. I did tried pcs cluster stop and start also.  As this node is destroyed and recreated via terraform code it is kind of reset now dont know how to join the node.

**Comment by RajasekarArumugam28** [comment]
Hi @ioguix , Please suggest how to remove failcount on pg1

**Comment by RajasekarArumugam28** [comment]
okay leave it @ioguix , I fixed the issue with pcs resource cleanup pgsqld , it works. thanks for the reply one again.

**Comment by ioguix** [comment]
> We dont have any fencing or watchdog enabled

Well, so PAF will not work properly then. Make sure to read our documentations about that.

> Usually when I start the node via pcs it will demote and start the slaves as standby

Make sure to read the documentation about that as well. When joining a node, you should make sure the locale PostgreSQL is shut downed as a standby.

>  I am not sure how to remove the failcount and start the cluster via pcs

As the manual page of `pcs` says: `pcs resource failcount reset <resource id> [node]`

But you can use `crm_resource` if you prefer: https://clusterlabs.org/pacemaker/doc/2.1/Pacemaker_Explained/html/operations.html#failure-counts
