### ISSUE TITLE
promotion fails if LSN cannot be determined for other nodes

### ISSUE THREAD

**Issue by ryandbair** [ClusterLabs/PAF#9]
During promotion, the program attempts to determine if this node has the highest LSN of all members in the partition. If the LSN of any node cannot be determined an error is returned and promotion fails. 

This can be problematic in two scenarios:
1. Postgres failed on the old master but the node is still running because there is no STONITH. 
2. There is a node in the partition which is not running postgres. 

In either case, retrieving the LSN from the node will fail and the promotion will fail. 

If we can limit the check to nodes that have healthy postgres instances, that would be ideal. Otherwise it might make sense just to log this as a notice/warn and move onto the next node.

**Comment by ioguix** [comment]
Hello,

You are right. We have to find a solution for these scenario.

I believe the best solution would be to implement the enhancement described in issue #1. Environment vars `OCF_RESKEY_CRM_meta_notify*`[1] are supposed to describe the current status of nodes and resources and what the CRM is trying to achieve in the current transition.

This will be implemented in the next release of PAF.

Thank you for this report.

[1] http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html-single/Pacemaker_Explained/#_multi_state_notifications

**Comment by ioguix** [comment]
Hello @ryandbair,

I just pushed a patch on the master branch to refactor this. By any chance, do you have some time to test it in your context?

We still use `crm_node --partition` in one place in the code, but only during the monitor action. That means the RA will still set master score of 0 on node where the resource has no clone, but this is not related to this issue and it shouldn't be a big deal for now. I'll work on this one later as well.

Regards,

**Comment by ryandbair** [comment]
Howdy, I'll be testing this and #10 in my test environment tomorrow. I'll update with the results.

**Comment by ryandbair** [comment]
Promotion does not work on CentOS 6 with this change since the provided `attrd_updater` command does not support the `--private` flag. 

https://github.com/dalibo/PAF/blob/cec43096449b8bff8ee0426685724f40f2b0cac4/script/pgsqlms#L68

**Comment by ioguix** [comment]
Hello @ryandbair.

Well, this is really annoying. `--private` was added in 1.1.13. I did not realized CentOS 6 was stucked with 1.1.12. Any chance you can update to this version?

I can think of some refactoring in the code to avoid using this, but they are quite large and would require another bunch of time and numerous tests:
  * the election process would require direct connections to postgres instances to check their LSN in live
  * keeping track of the active slave list or transition objective (switchover, resource recovery) etc between actions in a single transition would require...to use a status files.

I am quite hesitating between going backward to support old versions of Pacemaker from mid 2014 with some hacks or staying close to the modern side of the project :-(

**Comment by ioguix** [comment]
So back to this issue.

A new branch v1.1 has been created to support older stacks. See #22 as well about this. Current master branch will be the v2.0 version, uncompatible with EL6 distros.

Could you give the v1.1 branch a test? Thank you!

**Comment by blogh** [comment]
Hi,

I am stucked with Ubuntu 14.04 and pacemaker 1.1.10. So i could try PAF 1.0.2 and PAF 1.1.
If i understood correctly, it works as expected in 1.1

If i kill the master's postmaster on PAF 1.0.2

```
Online: [ x64lmwbio9f-priv x64lmwbio9g-priv ]

Full list of resources before:

 Resource Group: master-group
     vip-master (ocf::heartbeat:IPaddr2):       Started x64lmwbio9g-priv
     vip-rep    (ocf::heartbeat:IPaddr2):       Started x64lmwbio9g-priv
 Master/Slave Set: msPostgresql [pgsqlsrv]
     Masters: [ x64lmwbio9g-priv ]
     Slaves: [ x64lmwbio9f-priv ]
 Clone Set: fencing [st-null]
     Started: [ x64lmwbio9f-priv x64lmwbio9g-priv ]
```



`Jun  2 17:04:06 x64lmwbio9g pgsqlms(pgsqlsrv)[12346]: ERROR: _confirm_stopped: instance "pgsqlsrv" controldata indicates a running primary instance, the instance has probably crashed`
=> cannot restart on local node, the node on x64lmwbio9g-priv is fenced

`Jun  2 17:04:11 x64lmwbio9f pgsqlms(pgsqlsrv)[12866]: CRIT: pgsql_promote: can not get LSN location for "%s" x64lmwbio9g-priv`
=> cannot promote because LSN of x64lmwbio9g-priv is not available.

```
Online: [ x64lmwbio9f-priv  ]
OFFLINE: [ x64lmwbio9g-priv ]

Full list of resources after :

 Resource Group: master-group
     vip-master (ocf::heartbeat:IPaddr2):       Stopped
     vip-rep    (ocf::heartbeat:IPaddr2):       Stopped
 Master/Slave Set: msPostgresql [pgsqlsrv]
     Slaves: [ x64lmwbio9f-priv ]
     Stopped: [ x64lmwbio9g-priv ]
 Clone Set: fencing [st-null]
     Started: [ x64lmwbio9f-priv ]
     Stopped: [ x64lmwbio9g-priv ]

```
===> With PAF 1.1, the master is restarted on the local node.
	 

	 
If i kill the master's postmaster on PAF 1.0.2

```
Online: [ x64lmwbio9f-priv x64lmwbio9g-priv ]

Full list of resources before:

 Resource Group: master-group
     vip-master (ocf::heartbeat:IPaddr2):       Started x64lmwbio9g-priv
     vip-rep    (ocf::heartbeat:IPaddr2):       Started x64lmwbio9g-priv
 Master/Slave Set: msPostgresql [pgsqlsrv]
     Masters: [ x64lmwbio9g-priv ]
     Slaves: [ x64lmwbio9f-priv ]
 Clone Set: fencing [st-null]
     Started: [ x64lmwbio9f-priv x64lmwbio9g-pri

```
`Jun  2 17:23:34 x64lmwbio9f pgsqlms(pgsqlsrv)[14491]: ERROR: _confirm_stopped: instance "pgsqlsrv" controldata indicates a running secondary instance, the instance has probably crashed`
=> cannot restart on local node, the node on x64lmwbio9f-priv is fenced 

```
Online: [ x64lmwbio9g-priv ]
OFFLINE: [ x64lmwbio9f-priv ]

Full list of resources after :

 Resource Group: master-group
     vip-master (ocf::heartbeat:IPaddr2):       Started x64lmwbio9g-priv
     vip-rep    (ocf::heartbeat:IPaddr2):       Started x64lmwbio9g-priv
 Master/Slave Set: msPostgresql [pgsqlsrv]
     Masters: [ x64lmwbio9g-priv ]
     Stopped: [ x64lmwbio9f-priv ]
 Clone Set: fencing [st-null]
     Started: [ x64lmwbio9g-priv ]
     Stopped: [ x64lmwbio9f-priv ]
```
	 
===> With PAF 1.1, the standby is restarted on the local node.

**Comment by ioguix** [comment]
Hello @blogh 

Thank you for your tests. This behaviors are the one expected.

PAF 1.0.x is not able to recover a pgsql instance that was not stopped properly. This is a new feature in PAF 1.1.x.

1.0.x will be deprecated as soon as we could release 1.1.0.

Regards,

**Comment by blogh** [comment]
Your welcome, I can run additionnal tests if needed. We are testing the solution in my company right now.

**Comment by ioguix** [comment]
hi @blogh

Well, we are interested about any kind of tests and report.

Focus on 1.1.x if you are under EL6 and 2.0.x or 2.0_dev  for EL7 and Debian 8 :-)

We plan to release 2.0 as soon as possible after some doc update, tests and projects related tasks. 1.1.x is for deprecated systems and will be released later.

Cheers,

**Comment by dud225** [comment]
Hello

I've met this issue on a 2-nodes cluster when putting one of the nodes in maintenance mode.

Detailed scenario : 
* cluster composed of node1 & node2, stonith-enabled=false ; node1 runs as PG master role & node2  as slave role
* node2 is put into maintenance mode, PG becomes unmanaged on that node
* restart pgsql-ha on node1, promote fails and PG stays in slave role : 
```
crmd:   notice: te_rsc_command:	Initiating promote operation pgsqld_promote_0 locally on node1 | action 6
crmd:     info: do_lrm_rsc_op:	Performing key=6:305:0:e1868574-69ff-4e11-bfbb-f73b5e55dd21 op=pgsqld_promote_0
lrmd:   notice: operation_finished:	pgsqld_promote_0:3065:stderr [ 2016/11/21_10:19:34  INFO: pgsql_promote: "pgsqld" currently not running, starting it ]
lrmd:   notice: operation_finished:	pgsqld_promote_0:3065:stderr [ 2016/11/21_10:19:35  INFO: pgsql_start: instance "pgsqld" started ]
lrmd:   notice: operation_finished:	pgsqld_promote_0:3065:stderr [ 2016/11/21_10:19:35  CRIT: pgsql_promote: can not get current node LSN location ]
crmd:   notice: process_lrm_event:	Result of promote operation for pgsqld on node1: 1 (unknown error) | call=101 key=pgsqld_promote_0 confirmed=true cib-update=516
crmd:   notice: process_lrm_event:	node1-pgsqld_promote_0:101 [ 2016/11/21_10:19:34  INFO: pgsql_promote: "pgsqld" currently not running, starting it\n2016/11/21_10:19:35  INFO: pgsql_start: instance "pgsqld" started\n2016/11/21_10:19:35  CRIT: pgsql_promote: can not get current node LSN location\n ]
cib:     info: cib_perform_op:	+  /cib/status/node_state[@id='1']/lrm[@id='1']/lrm_resources/lrm_resource[@id='pgsqld']/lrm_rsc_op[@id='pgsqld_last_0']:  @operation_key=pgsqld_promote_0, @operation=promote, @transition-key=6:305:0:e1868574-69ff-4e11-bfbb-f73b5e55dd21, @transition-magic=0:1;6:305:0:e1868574-69ff-4e11-bfbb-f73b5e55dd21, @call-id=101, @rc-code=1, @last-run=1479723573, @last-rc-change=1479723573, @exec-time=1279
crmd:  warning: status_from_rc:	Action 6 (pgsqld_promote_0) on node1 failed (target: 0 vs. rc: 1): Error
crmd:     info: abort_transition_graph:	Transition aborted by operation pgsqld_promote_0 'modify' on node1: Event failed | magic=0:1;6:305:0:e1868574-69ff-4e11-bfbb-f73b5e55dd21 cib=0.168.1 source=match_graph_event:310 complete=false
crmd:     info: match_graph_event:	Action pgsqld_promote_0 (6) confirmed on node1 (rc=1)
crmd:     info: process_graph_event:	Detected action (305.6) pgsqld_promote_0.101=unknown error: failed
crmd:  warning: status_from_rc:	Action 6 (pgsqld_promote_0) on node1 failed (target: 0 vs. rc: 1): Error
crmd:     info: abort_transition_graph:	Transition aborted by operation pgsqld_promote_0 'modify' on node1: Event failed | magic=0:1;6:305:0:e1868574-69ff-4e11-bfbb-f73b5e55dd21 cib=0.168.1 source=match_graph_event:310 complete=false
crmd:     info: match_graph_event:	Action pgsqld_promote_0 (6) confirmed on node1 (rc=1)
crmd:     info: process_graph_event:	Detected action (305.6) pgsqld_promote_0.101=unknown error: failed
crmd:   notice: te_rsc_command:	Initiating promote operation pgsqld_promote_0 locally on node1 | action 8
crmd:     info: do_lrm_rsc_op:	Performing key=8:307:0:e1868574-69ff-4e11-bfbb-f73b5e55dd21 op=pgsqld_promote_0
lrmd:   notice: operation_finished:	pgsqld_promote_0:3343:stderr [ 2016/11/21_10:19:42  INFO: pgsql_promote: promote complete ]
crmd:   notice: process_lrm_event:	Result of promote operation for pgsqld on node1: 0 (ok) | call=117 key=pgsqld_promote_0 confirmed=true cib-update=524
cib:     info: cib_perform_op:	+  /cib/status/node_state[@id='1']/lrm[@id='1']/lrm_resources/lrm_resource[@id='pgsqld']/lrm_rsc_op[@id='pgsqld_last_0']:  @operation_key=pgsqld_promote_0, @operation=promote, @transition-key=8:307:0:e1868574-69ff-4e11-bfbb-f73b5e55dd21, @transition-magic=0:0;8:307:0:e1868574-69ff-4e11-bfbb-f73b5e55dd21, @call-id=117, @last-run=1479723581, @last-rc-change=1479723581, @exec-time=1325, @queue-time=0
crmd:     info: match_graph_event:	Action pgsqld_promote_0 (8) confirmed on node1 (rc=0)
```

**Comment by ioguix** [comment]
hello @dud225,

Your scenario indeed trigger this issue. But you are not supposed to trigger some actions on your master when only half of your cluster is in maintenance.

If you need to do some maintenance on both nodes, put all the cluster or at least the whole in resource in maintenance mode.

Considering the 2nd scenario of OP @ryandbair, where a node does not host any pgsql resource related to the cluster, then you should force the cluster to avoid this node for this resource. Here is a sample setup using pcs where the ms resource is called `pgsql-ha` and the node to avoid is called `srv3`:

~~~
pcs constraint location pgsql-ha rule resource-discovery=never score=-INFINITY \#uname eq srv3
~~~

In this command, `resource-discovery=never` is really important to avoid the "probe" action to discover the status of the resource on the node. This probe action would trigger an error during `validate_all()`.

Considering the 1st scenario of OP @ryandbair, I still need some more time to find if a solution is possible. But clearly, we wrote PAF considering there MUST be some fencing resource in the cluster.

**Comment by ge-fa** [comment]
> But clearly, we wrote PAF considering there MUST be some fencing resource in the cluster.

Which is totally valid and fine. There is no other way, even if some people don't believe this, or set up their systems differently. Some links quite worth to check out:

- http://clusterlabs.org/doc/crm_fencing.html
- http://advogato.org/person/lmb/diary/105.html
- https://ourobengr.com/ha/
- https://ourobengr.com/stonith-story/

**Comment by ioguix** [comment]
Thank you @ge-fa,

I knew these links. While you rose them here, it appears to me it might be good to point new comers to them. So I added them to our [fencing documentation](http://dalibo.github.io/PAF/fencing.html).

Thanks,

**Comment by ioguix** [comment]
To resume this issue, there is only one scenario to study: is it possible to avoid failures during failover when the master fails, but there is no stonith around? In this scenario where the master node is still up, PAF will still try to get the LSN location from the master before promoting the designated slave, leading to the failure

The only easy and reasonable solution is to have some stonith device.
 
But we could still study some other possible solutions:
  * this is somewhat related to #31
  * maybe we could use watchdog (eg softdog) for self fencing. This need some more study and tests to define if it is a possible solution, then to document it.

any other idea is welcomed.

**Comment by ioguix** [comment]
Hi,

Using watchdog has been documented, at least for linux EL7 family. See: http://dalibo.github.io/PAF/CentOS-7-admin-cookbook.html#setting-up-a-watchdog

**Comment by ioguix** [comment]
I believe this has been fixed long ago. Now, during the pre-promote action, the rsc-to-be-promoted build a list of nodes that is supposed to set their lsn-location, based on the OCF_NOTIFY_ENV values.

During promotion, only LSN from the nodes that are supposed to be started are checked, based on the previous list built during the pre-promote action. So the LSN from the failing master should not be checked anymore.
